### ISSUE TITLE
Link error catalog to the api documents

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#10278]
### Issue
According to the latest REST API implementations, we have introduced new error codes for each scenario. Currently, some of the error codes are documented in [1]. We also have several error codes documented in [2].  Also currently we don't have a section in API docs, pointing to the error codes.

### TODO
- [ ] Link doc [1] and [2].
- [ ] Link doc [1] with api docs and [3].
- [ ] Add missing API error codes to the doc [1]

[1] - https://is.docs.wso2.com/en/latest/references/error-catalog/
[2] - https://is.docs.wso2.com/en/latest/develop/error-codes-and-descriptions/#error-codes-and-descriptions
[3] -  https://is.docs.wso2.com/en/latest/develop/rest-apis/

**Comment by pulasthi7** [comment]
@sherenewso2 @gomathyk Are we good to close this issue?

**Comment by sherenewso2** [comment]
@pulasthi7 No. We still didn't get the required info for missing error codes.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
