### ISSUE TITLE
Issues encountered during OIDC conformance suite run

### ISSUE THREAD

**Issue by Yasasr1** [wso2/product-is#10408]
**This is a list of all issues encountered when running OIDC conformance suite against IS 5.11.0 beta 5**

**Failures**

- [x] [State missing from error response](https://github.com/wso2/product-is/issues/10433)
- [x] [Authorization requests with response_type=id_token token fail](https://github.com/wso2/product-is/issues/10407)
- [x] ['error' Field from authorization endpoint error response has an unexpected value](https://github.com/wso2/product-is/issues/10790)
- [x] ["server_error" from authorization endpoint when "response_type=code id_token"](https://github.com/wso2/product-is/issues/10932)
- [x] [jQuery import missing from oauth_response.html](https://github.com/wso2/product-is/issues/10939)
- [x] [The HTTP method used in authorization error response in form post mode is not 'POST'](https://github.com/wso2/product-is/issues/11316)
- [x] ['updated_at' claim from userinfo endpoint response is in milliseconds](https://github.com/wso2/product-is/issues/11317)
- [x] [State parameter is missing in the Error response in the Form Post mode](https://github.com/wso2/product-is/issues/12693)
- [x] [at_hash claim available in the id_token when an access token is not returned](https://github.com/wso2/product-is/issues/12762)

**Warnings**

- [x] [Sending access token through request body to oauth2/userinfo](https://github.com/wso2/product-is/issues/10387)
- [x] [ID token doesn't contain acr claims](https://github.com/wso2/product-is/issues/10400)
- [x] [Access token not revoked after using the same authorization code](https://github.com/wso2/product-is/issues/10401)
- [ ] [Add auth_time to ID token](https://github.com/wso2/product-is/issues/10391)
- [ ] [Error when adding "Middle Name" claim value](https://github.com/wso2/product-is/issues/10638)
- [ ] [Claims requested through scope parameter are available in the ID Token when there is an Access Token](https://github.com/wso2/product-is/issues/12696)
- [ ] [Claims not found in id_token for Implicit requests with claims as essential](https://github.com/wso2/product-is/issues/12695)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
