### ISSUE TITLE
[Development] Bind `templateId` to Application Listing Component

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#10681]
## Feature/Improvement
> Add `templateId` to Application Listing Component

## Description
> Currently, Application REST APIs [listing endpoint](https://is.docs.wso2.com/en/latest/develop/application-rest-api/#/Applications/getAllApplications) don't provide the templateId. **** (Now the BE implementation is completed with https://github.com/wso2/product-is/issues/10681#issuecomment-1169497984). In Console, we are displaying the template name on the application edit page as follows.

<img width="702" alt="Screen Shot 2020-12-04 at 6 20 12 PM" src="https://user-images.githubusercontent.com/25959096/101165880-65a36e80-365d-11eb-9751-3ddb90b2bedc.png">

And we are not showing the template in the listing which gives bad UX.

<img width="750" alt="Screen Shot 2020-12-04 at 6 21 25 PM" src="https://user-images.githubusercontent.com/25959096/101165983-8c61a500-365d-11eb-9795-8de9eeaf5cd0.png">

**Describe the solution you propose**
> Improve the Application listing endpoint to include `templateId` in the response and add a label to the application listing item to display the `templateId` and later on implement to filter applications based on that criteria.

## Design
> https://github.com/wso2/product-is/issues/14114

## Effort and Timeline

| Effort Type                           | Estimation - Budgeted        | Estimation - Definitive | Actual Time
| -------------------------- | --------------------------- |--------------------------- | --------------------------- |
| BE                        | 10                         | 10                        | XX
| FE                        | 10                          | 10                         | XX
| SRE                       | 0                          | 0                         | 0
| QA                       | 2                          | 2                         | XX
| DoC                       | 0                          | 0                         | XX
| _Total_                       | 22                          | 22                         | _XX_

 Expected date in prod: 27-07-2022
 Delivered date in prod: DD-MM-YYYY

### Task breakdown

**Phase 1**

**MVP 1:**
- [x] Design - https://github.com/wso2/product-is/issues/14114 _(In-Progress)_

**MVP 2:**
- [x] Backend Implementation
    - The backend is being fixed with the following by @VivekVinushanth 
    > https://github.com/wso2/product-is/issues/10681#issuecomment-1169497984

**MVP 3:**
- [x] Displaying `templateId` in application listing item
    - [x] Update the frontend API service layer.
    - [x] Update application listing table item.
    - [x] Implement necessary styles to show the `templateId` tag.

**MVP 4:**
- [ ] Consume `templateId` for filtering
    - [ ] Add the `templateId` to advanced search criteria.

### Delivery plan
> N/A

### Check Items
  
- [x] **Design reviews**
- [x] Development Preview
- [ ] Implementation Demo

**Comment by mefarazath** [comment]
With the current schema, we have few limitations in supporting this without introducing perf hits.

In the current schema, application basic information is maintained in the table '**SP_APP**', while the templateID is stored in the '**SP_METADATA**' table.

![image](https://user-images.githubusercontent.com/5237653/105297577-236bc780-5be0-11eb-8852-f4877d4015a5.png)


Application Listing works on the SP_APP table. If we are to support sending templateID as an attribute in the application list response, then

1. Fetch the templateID from SP_METADATA for each listed application before building the list response
2. Modify the list application query to join SP_APP and SP_METADATA table
3. Make templateID a dedicated column in SP_APP

* Approach 1 has a perf impact with additional DB query added to each application listed in the list response
* Approach 2 will make the DAO logic complex and also have a perf impact when the number of apps in large
* Approach 3 - In terms of performance and complexity this is the best options. However, this will introduce a schema change and a possible migration requirement.

**Comment by yasinmiran** [comment]
- [ ] Do a competitor analysis.
- [ ] Come up with design variants.
- [ ] Functionality - Template filtering.

**Comment by yasinmiran** [comment]
Implementation PRs did by @VivekVinushanth 

- https://github.com/wso2/identity-api-server/pull/366
- https://github.com/wso2/carbon-identity-framework/pull/4065
- https://github.com/wso2/product-is/issues/13944

Mapping related issue
- https://github.com/wso2-enterprise/asgardeo-product/issues/10967

**Comment by yasinmiran** [comment]
@malshan1998 please cherry-pick take the changelist of https://github.com/wso2/identity-apps/pull/3091 locally and test these changes work without any issue.

**Comment by malshan1998** [comment]
#### Weekly update summary - 29-07-2022

#### Current status
* Displays the template names in a separate column
* Put a PR upto previous point
* Resolved the issue of not displaying template names of Standard-Based Applications

#### Action items for next week
* Displaying the table headers
* Implementing a filter from templateId

**Comment by malshan1998** [comment]
#### Changing the milestone
Updated the milestone to August from July, since the development is still in progress. 
To do:
* Displaying the table headers
* Implementing a filter from templateId

**Comment by malshan1998** [comment]
#### Weekly update summary - 29-07-2022

#### Current status
* Displays the template names in a separate column
* Resolved the issue of not displaying template names of Standard-Based Applications
* PR reviewed

#### Action items for next week
* Display table headers (Asgardeo only)
* Finalizing the delivery plan of implementing a filter from templateId (8th August)
* Finish E2E testing (10th August)

**Comment by malshan1998** [comment]
#### Weekly update summary - 17-08-2022

#### Current status
* PR for display of template name merged
* Currently working on table headers display of Asgardeo

#### Action items for next week
* Finish the table headers display
* E2E testing
* Adding filtering with templateId

**Comment by malshan1998** [comment]
#### Weekly update summary - 31-08-2022

#### Current status
* PR for display of template name merged
* PR for the table headers display and removal of description display has been put (not yet merged)
* The filtering by templateId was unassigned

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
