### ISSUE TITLE
Improvements to released SDK

### ISSUE THREAD

**Issue by ayshsandu** [wso2/product-is#10818]
There are several improvements to be done in the following authentication SDKs 

- [ ] .NET
- [ ] JAVA OIDC tomcat agent
- [ ] Java SAML tomcat Agent
- [ ] Android

In following aspects.

- [ ] Change component and package name from Asgardio to Asgardeo
- [ ] Functional testing
- [ ] Unit testing
- [ ] Integration testing
- [ ] Documentation update
- [ ] UX improvements in samples
- [ ] Further functionalities such as session management

**Comment by ayshsandu** [comment]
Improvements specific for .NET SDK
- [ ] [UX improvements for Windows (WPF) sample](https://github.com/wso2/product-is/issues/8104)
- [ ] - [Have side panal to show the personalized resouce file (installer conf)](https://github.com/wso2/product-is/issues/8110)
- [ ] - [Improve the installer to point a a resouce file](https://github.com/wso2/product-is/issues/8111)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
