### ISSUE TITLE
Support externalized webapp URLs in tenant qualified URL mode - Phase 1

### ISSUE THREAD

**Issue by mefarazath** [wso2/product-is#10953]
In Identity Server, we have the option of externalizing user-facing web apps such as the login portal, recovery portal, and connector endpoints such as TOTP, email OTP and SMS OTP portals.

Currently, we can only define some of these externalized URLs at the server level.

Externalized URL can be absolute URLs residing outside of IS and also custom contexts residing within IS. For example, our default authentication endpoint is https://localhost:9443/authenticationendpoint/login.do

This can be externalized as either,
- https://localhost:9443/security/login.do
- https://login.somedomain.com/login.do

When it comes to tenant qualified URLs feature, currently we do not have the capability to support externalized web apps. In order to support this,

**Phase I**

When the tenant qualified URLs feature is enabled

- If the URL externalized (or customized) is a relative one (ie. hosted within IS with a different context than default), then build the URL with tenant qualified path (/t/{tenantDomain} in the path)

- If the URL externalized is an absolute one, then we do not try to tenant qualify it.

- If no URLs are defined from configs, then build the tenant qualified URLs with the default context

A few identified points to fix
- [ ] ConfigurationFacade in Identity Framework that provides login, retry and recovery URLs
- [x] [TOTP](https://github.com/wso2-extensions/identity-outbound-auth-totp/pull/82) https://github.com/wso2/product-is/issues/10900
- [x] [Email OTP](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/110) https://github.com/wso2/product-is/issues/10931
- [ ] SMS OTP https://github.com/wso2/product-is/issues/10947
- [ ] Other connectors that involve redirecting users to a input page

[Phase II](https://github.com/wso2/product-is/issues/10989)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
