### ISSUE TITLE
Configure commonAuthCallerPath validating regrex via REST API

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#10976]
This PR https://github.com/wso2/carbon-identity-framework/pull/3267, adds a new UI element to SP configurations to register a return to URL or a regEx during IdP logout. The commonAuthCallerPath in the logout request is validated against this registered value.

We need to provide the same capability from the Application Management REST API

**Comment by RushanNanayakkara** [comment]
### Progress Update 

#### Tasks

- [x] Implement adding logoutReturnUrl parameter to the application models used in the application API.
   - [x] Merge public fix PRs
   - [ ] Merge wso2is-6.0.0 fix PRs
   - [ ] Merge wso2is-6.1.0 fix PRs
- [x] Update the docs 
  - [ ] Update docs for wso2is-7.0.0
  - [ ] Update docs for wso2is-6.1.0 
  - [ ] Update docs for wso2is-6.0.0

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
