### ISSUE TITLE
[SCIM2] Optional functionalities in specification which doesen't support in wso2 IS

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [wso2/product-is#10995]
**Is your suggestion related to an experience ? Please describe.**
There are several missing optional functionalities we can add to current SCIM implementation.

**Describe the improvement**
Below are a list of suggestions we can add,

- [ ] [Sort functionality](https://github.com/wso2/product-is/issues/4362) [1]
- [ ] [Pagination in Group endpoint](https://github.com/wso2/product-is/issues/9237) [2]
- [ ] ["bulkId" Temporary Identifiers in  Bulk endpoint](https://github.com/wso2/product-is/issues/3300) [3]
- [ ] Circular Reference Processing in Bulk endpoint [4]
- [ ] Adding nested groups as members in group endpoint [5]
- [ ] Etag support [6] 
- [ ] [Filtering more operator support](https://github.com/wso2/product-is/issues/10123) [7]

**References**
[1]https://tools.ietf.org/html/rfc7644#section-3.4.2.3
[2]https://tools.ietf.org/html/rfc7644#section-3.4.2.4
[3]https://tools.ietf.org/html/rfc7644#section-3.7.2
[4]https://tools.ietf.org/html/rfc7644#section-3.7.1
[5]https://tools.ietf.org/html/rfc7643#page-26
[6]https://tools.ietf.org/html/rfc7644#section-3.14
[7]https://tools.ietf.org/html/rfc7644#section-3.4.2.2

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
