### ISSUE TITLE
Fix inconsistencies in Groups vs Roles separation 

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#11327]
Identity Server 5.11.0 introduced groups vs roles separation, by clearly separating the previous user grouping and permission assignment based on `roles`. However, this was not fully adapted to all the use cases. The end goal of this task is to identify and fix those inconsistent places.

The rest of this issue uses the following notations.

- USG
   - User Store Group
   - Maintained by user store managers.
   - A collection of users.
- IR
   - Internal Role
   - Maintained by Identity server for its internal tasks.
   - A collection of permissions.
- Role claim, wso2.role
    - http://wso2.org/claims/role 
- Roles claim
    - A new claim introduced to include IRs
    - http://wso2.org/claims/roles 
- SCIM Groups claim
    - urn:ietf:params:scim:schemas:core:2.0:User:groups
- SCIM Role claim
    - urn:ietf:params:scim:schemas:core:2.0:User:roles.default
   
**Following table describes the behavior of each key elements**

| 5.10.0	  | 5.11.0 - Current | 5.11.0 - Expected |
| ------------- | ------------- | ------------- |
| Both USG and IR denoted roles  | USG and IR are separated according to their definitions. If any USG in 5.10.0(a role having users assigned) has permissions assigned, a new IR containing the same permissions are created during 5.11 migration | Same as 5.11.0 current behavior |
| Role claim = USG+IR  | Role claim = USG+IR  | Role claim = USG+IR  |
| Roles claim = N/A  | Roles claim = N/A  | Roles claim = IR  |
| Groups claim = None | Groups claim = None  | Groups claim = USG  |
| SCIM Groups claim = USG+IR | SCIM Groups claim = USG  | SCIM Groups claim = USG  |
| SCIM Role claim = None | SCIM Role claim = IR  | SCIM Role claim = IR  |

**Research component to identify inconsistencies**

- [x] https://github.com/wso2/product-is/issues/11234

**Tasks**
- [x] Fix code base to handle claims related to groups and roles
   - Tracked in https://github.com/wso2/product-is/issues/11328
- [ ] Handle wso2.role claim as a legacy claim
   - Tracked in https://github.com/wso2/product-is/issues/11341
- [ ] SP role mapping and IDP role mapping
   - Tracked in https://github.com/wso2/product-is/issues/11330
- [ ] Role-based outbound provisioning
   - Trcked in  https://github.com/wso2/product-is/issues/11344
- [ ] OIDC groups claim in ID token, SAML role attribute
   - Tracked in https://github.com/wso2/product-is/issues/11345
- [x] Scope bounded authorization for access tokens
   - Tracked in https://github.com/wso2/product-is/issues/11346
- [ ] SCIM2 - role and groups claims
   - Tracked in https://github.com/wso2/product-is/issues/11347
- [x] Management console, Console App
   - Tracked in https://github.com/wso2/product-is/issues/11348

**Identified Issues**
- [x] Confusing value appears for `groups` claim
   - Tracked in https://github.com/wso2-enterprise/asgardeo-product/issues/1799
- [x] Viewing personal information in the my account is broken with #11328 and #11347 changes patched.

**Migration**
- [ ] Tasks for the migration
   - Tracked in https://github.com/wso2/product-is/issues/11340

**Backport to 5.11.0**
- [ ] Deploy update

**Use a separate configuration to ensure backward compatibility for IS 5.11.0**
- [x] Switch current configuration to a new one

**Fix integration tests**
- [ ] Fix integration tests to use `groups` claim.
   - PR: https://github.com/wso2/product-is/pull/11507

**Comment by tharindu-bandara** [comment]
Use a new configuration to enable inconsistencies fixes.

**Comment by tharindu-bandara** [comment]
Status Update: Locally testing all the changes against the product integration test suit
