### ISSUE TITLE
Properly handle claims related to groups and roles from user core 

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#11328]
_This issue is a subtask of https://github.com/wso2/product-is/issues/11327, thus continues the discussion from there_

There are three claims to represent groups and roles. And all of these should be properly handled from the user core in the following manner.

- Role claim
   - http://wso2.org/claims/role
   - A legacy claim used to represent roles when groups vs roles separation were not available.
   - This claim needs to be kept intact and will contain both USG and IR.
- Roles claim
   - http://wso2.org/claims/roles
   - A newly introduced claim which will contain IRs
   - Need to add the required logic from the user core level such that the user core will especially handle this claim to include IRs.
- Groups claim
   - http://wso2.org/claims/groups
   - This is an existing, unused claim
   - Need to add the required logic from the user core level such that the user core will especially handle this claim to include USGs.

**Tasks**

- [x] Add new wso2.roles claim into the claim-mgt.xml file
- [x] Add a new attribute for the wso2.roles claim in both JDBC and LDAP.
- [x] Add code logic to handle wso2.roles claim while retrieving.
- [ ] Review and merge PRs
   - [ ] Conduct code review
   - [ ] Iterate and fix PRs
   - [ ] Update and close the issue
