### ISSUE TITLE
Switch role claim URI to groups claim

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#11330]
_This issue is a subtask of #11327, thus continues the discussion from there._

_Depends on the `groups` claim changes introduced with #11328._

Need to switch to the wso2.groups claim for the claim URI in both SP and IDP role mappings. 

**Tasks**
_SP role mapping_
- [x] Switch to SCIM2/groups endpoint listing local roles in console based on the b/c config.
   - If b/c required, the list should have both IR and USG
   - Or else, it lists only groups
- [x] Fix SP APP validation in the identity framework
   - with b/c: validate against wso2.role claim
   - without b/c: validate against wso2.group claim 
- [x] Test and verify adding a group mapping works

_IDP role mapping_
- [x] Switch to SCIM2/groups endpoint listing local roles in console based on the b/c config.
   - If b/c required, the list should have both IR and USG
   - Or else, it lists only groups
- [x] Fix SP APP validation in the identity framework
   - with b/c: validate against wso2.role claim
   - without b/c: validate against wso2.group claim 
- [x] Test and verify adding a group mapping works

_Support role mapping for newly introduced Roles and Groups claims_
- [x] Check where the role mapping is done during inbound and outbound authentication, and outbound provisioning.
   - [x] Handle framework logic for role mapping : https://github.com/wso2/carbon-identity-framework/pull/3423 
- [x] Inbound authentication - OAuth : Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1562
- [x] Inbound authentication - SAML: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Inbound authentication - STS:  There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Inbound authentication - Passive STS:  There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Inbound authentication - Kerberos KDC: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - SAML2 Web SSO: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - OAuth2/OIDC: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - WS-FED Passive: OAuth2/OIDC: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Facebook: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Microsoft: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Google: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - SMS OTP: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Twitter: There is no role mapping logic.
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Email OTP: There is no role mapping logic
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Yahoo: There is no role mapping logic
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound auth - Office 365: There is no role mapping logic
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound Provisioning Connector - Google: There is no role mapping logic
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound Provisioning Connector - Salesforce: There is no role mapping logic
   - [x] Checked codebase
   - [x] Confirmed
- [x] Outbound Provisioning Connector - SCIM: There is no role mapping logic
   - [x] Checked codebase
   - [x] Confirmed

- [ ] Integration tests to ensure role, roles, and groups claims are properly mapped when configured role mapping.
 
**Migration Tasks: included in https://github.com/wso2/product-is/issues/11340**

**Comment by tharindu-bandara** [comment]
There is no role mapping logic for SAML attribute statement generation. Need to verify this.

**Comment by tharindu-bandara** [comment]
Review comments:

- [ ] Need to change the UI label naming from `role` to `groups` in the sp and idp role mapping section
