### ISSUE TITLE
Handle wso2.role as a legacy claim

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#11341]
_This issue is a subtask of #11327, thus continues the discussion from there._

`wso2.role` claim contains both USG and IR. Moving forward, we need to use `wso2.groups` and `wso2.roles` claims instead, in order to have an accurate separation. 

Therefore other than in a migrated setup, the `wso2.role` claim should not be visible to identity administration and this behavior can be toggled with the b/c config option.

**Tasks**
- [x] Mark role claim as not supported by default
- [x] MGT Console
   - [x] Remove from user profile
   - [x] Remove from listing local claims
   - [x] Remove from the local claim set in add external role and edit external role
   - [x] Remove from local claim listing in SP requested claims
   - [x] Remove from local claim listing in IDP claim configs
- [x] Console app
   - [x] Remove from user profile
   - [x] Remove from listing local claims
- [ ] Merge PRs
   - [ ] Review and merge PRs
   - [ ] Update issue
