### ISSUE TITLE
Switch to groups for role based outbound provisioning

### ISSUE THREAD

**Issue by tharindu-bandara** [wso2/product-is#11344]
_This issue is a subtask of #11327, thus continues the discussion from there_

Currently, role-based outbound provisioning is based on certain roles. This needs to be switched to groups.

For example, say there exists a group named `accountants`. If the user `john` is assigned to the `accountants` group, `john` should be outbound provisioned.

**Tasks**
- [ ] List down groups in the `outbound provisioning roles` section and change the title of the section to groups based on the b/c config option.
- [ ] Fix backend validation to be based on the `wso2.groups` claim.
- [ ] Fix internal implementation of outbound provisioning to use wso2.groups.

**Comment by tharindu-bandara** [comment]
No need to do internal code changes as groups are a subset of roles in the current implementation. From the console app, we will only allow adding groups as the provisioning role and change the headings to reflect the `groups` term.

**Comment by tharindu-bandara** [comment]
Fix mgt console headings

**Comment by tharindu-bandara** [comment]
Review comments:

- [ ] Change mgt console UI naming from `role` to `group`
