### ISSUE TITLE
Refer tenant from tenanted apis/endpoints

### ISSUE THREAD

**Issue by piraveena** [wso2/product-is#11363]
**Is your suggestion related to an experience ? Please describe.**
Currently, we infer tenant from usernames or other parameters in various places. (Eg in email sending flows, we infer tenant domain from the email template url.) So we need to avoid referring tenant domain from username or other query parameters and improve it to refer from path param if tenanted url is supported.

**Tasks**
- [ ] Check email related flows (Self registration, Ask password, Email verification, Password reset)
- [ ] Local Authenticators (Basic, emailotp, smsotp, totp etc)
- [ ] Inbound protocols
- [ ] Need to identify the other flows which get impact from this

**Comment by piraveena** [comment]
- For email-related flows, tenant domain is taken from email templates if tenant qualified url is not enabled. Otherwise, we take it from context when tenant qualified url is not enabled. So we can't remove it from the email template since we read tenant domain from tenant if the tenant qualified url is not enabled

- [ ] Fix issues related to email templates when tenant qualified url is enabled

- Flows related to authenticators.
- [ ]  Email otp
- [ ] SMS otp
- [ ] TOTP
- [ ] Basic authenticator

**Comment by piraveena** [comment]
- Flows related to authenticators.
- [ ]  Email otp
- [ ] SMS otp
- [ ] TOTP
- [ ] Basic authenticator
