### ISSUE TITLE
[SCIM2] Features / Improvements / Bugs

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#11403]
**Features** 

- [ ] [Sorting support for SCIM2 API](https://github.com/wso2/product-is/issues/4362)
- [ ] [Support "bulkId" Temporary Identifiers for bulk uploaded via SCIM](https://github.com/wso2/product-is/issues/3300)
- [ ] [Support Etag for resource versioning](https://github.com/wso2/product-is/issues/13766)
- [x] [Regex is not getting validated for claims in SCIM API](https://github.com/wso2/product-is/issues/9816)
- [x] [Ability to define different enterprise user claims in tenant wise](https://github.com/wso2/product-is/issues/8896) 
- [ ] [Standardize enterprise User extension schema](https://github.com/wso2/product-is/issues/9022)
- [ ] [SCIM Compliance Test suite](https://github.com/wso2/product-is/issues/8910)
- [ ] [SCIM Performance Test Suite](https://github.com/wso2/product-is/issues/8910)
- [ ] [Multi-attribute filtering support for SCIM2 group endpoint](https://github.com/wso2/product-is/issues/6061)
- [ ] https://github.com/wso2/product-is/issues/15560

**Improvements**

- [ ] [Support pagination for SCIM2.0 Groups endpoint](https://github.com/wso2/product-is/issues/9237)
- [ ] [SCIM 2.0 schemas endpoint support for group schemas](https://github.com/wso2/product-is/issues/8896)
- [ ] [Refactoring pagination logic in SCIM filtering and listing](https://github.com/wso2/product-is/issues/10123)
- [ ] [Validating the current password when updating the password via SCIM2](https://github.com/wso2/product-is/issues/10014)
- [ ] [Improvement for SCIM2 primary flag for complex email attribute without type](https://github.com/wso2/product-is/issues/9247)
- [ ] [Get Group call fails when the user list of the role is large](https://github.com/wso2/product-is/issues/9201)
- [ ] [SCIM APIs given 500 if one of the userstore connection went down](https://github.com/wso2/product-is/issues/7775)
- [ ] [Filtering support for OR and NOT](https://github.com/wso2/product-is/issues/13915)
- [ ] [Performance improvements to SCIM Roles Patch groups and SCIM Roles GET](https://github.com/wso2/product-is/issues/15207)

**Bugs**

- [ ] [SCIM2 included and excluded attribute filters are expecting an invalid attribute URI](https://github.com/wso2/product-is/issues/11092)
- [ ] [Schema violations in attriute definitions](https://github.com/wso2/product-is/issues/10984)  
- [ ] [Return 500 when patching non-existing group instead of 404](https://github.com/wso2/product-is/issues/11248)
- [ ] [Inconsistency in enforcing mutability of claims](https://github.com/wso2/product-is/issues/11194)
- [ ] [Setting two primary emails are possible via SCIM API](https://github.com/wso2/product-is/issues/10033)
- [ ] [SCIM 2.0 Role API not retrieve the meta attribute "resourceType"](https://github.com/wso2/product-is/issues/9177)
- [ ] [SCIM 2 emails field handling is different than in the RFC](https://github.com/wso2/product-is/issues/7304)
- [ ] [Issues in SCIM PATCH Request](https://github.com/wso2/product-is/issues/11678)
- [ ] [Multiple issues on using the filter in SCIM2 Users Endpoint](https://github.com/wso2/product-is/issues/11807)
- [x] [Performance issue when using the SCIM 2.0 PATCH /scim2/Roles/{{id}} REST API](https://github.com/wso2/product-is/issues/15154)

**Docs**

- [ ] [Incomplete SCIM API docs](https://github.com/wso2/product-is/issues/12127)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
