### ISSUE TITLE
Improve product startup time

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#11410]
**Describe the issue:**
We have identified the following tasks that will improve the product startup improvement,

- [x] [Reduce file read for tenant artifact during the start up](https://github.com/wso2/carbon-kernel/issues/2935)
- [x] [Improving web app classloaders](https://github.com/wso2/product-is/issues/6393)
- [x] [Remove Application Server usecases from webapp deployment](https://github.com/wso2/carbon-deployment/pull/349)
- [x]  [Merging the api web apps](https://github.com/wso2/product-is/issues/11425)
- [x] [Avoid unnecessary JAR scanning for TLDs for the API webapps](https://github.com/wso2/product-is/issues/11531)
