### ISSUE TITLE
Maintain the identity caches in the tenant space

### ISSUE THREAD

**Issue by senthalan** [wso2/product-is#11690]
**Is your suggestion related to an experience? Please describe.**
In the current system, all the identity caches are maintained in super tenant with a capacity of 5000. This affects the throughput of the system when the tenant count increases. For example, when tenant count increases the service provider cache will be filled when the tenant count 500 (10 SP per tenant).

So ideally in a multi-tenant env offering,  need to maintain the tenant data cache in the tenant space and those caches need to be removed with tenant unloading. We also need to come up with a realistic capacity for each type of cache without affecting memory consumption.

**Comment by senthalan** [comment]
The following set of identity caches needs to be moved to tenant space, (separated by the repository)

## Phase 1
### carbon-identity-framework 
- [ ] [Service Provider ](https://github.com/wso2/carbon-identity-framework/pull/3499)
- [x] [Identity Provider](https://github.com/wso2/carbon-identity-framework/pull/3500)
- [x] [CORS](https://github.com/wso2/carbon-identity-framework/pull/3501)
- [x] [Claim management](https://github.com/wso2/carbon-identity-framework/pull/3502)
- [x] [Provisioning](https://github.com/wso2/carbon-identity-framework/pull/3503)
- [ ] Authentication context and Session
### identity-inbound-auth-oauth 
- [ ] OAuthCache, JWKSCache, ClaimCache, ClaimMetaDataCache and etc 
### identity-inbound-auth-saml
- [ ] SAMLSSOParticipantCache, SAMLSSOSessionIndexCache, SessionDataCache.java and etc 

## Phase 2
- [ ] User Store on-prem agent in identity-userstore-onprem-agent
- [ ] InMemoryIdentityDataStore in identity-governance
- [ ] FIDO2Cache in identity-local-auth-fido
- [ ] Entitlement
- [ ] OAuth2 JWT grant in identity-oauth2-grant-jwt
- [ ] Basicauth JWT in identity-local-auth-basicauth
- [ ] CRLCache in identity-x509-commons
- [ ] MutualTLSJWKSCache and JWTCache in identity-oauth-addons
- [ ] TicketGrantingTicketCache in identity-inbound-auth-cas
- [ ] SessionDataCache in identity-inbound-auth-sts
- [ ] OpenIDBaseCache in identity-inbound-auth-openid

**Comment by senthalan** [comment]
Due to https://github.com/wso2/product-is/issues/11381, the OIDCSessionParticipantCache cookie of identity-inbound-auth-oauth is not moved to tenanted path.
