### ISSUE TITLE
Enhance JIT provisioning feature

### ISSUE THREAD

**Issue by GANGANI** [wso2/product-is#12017]
**Description**

This issue is to track the following JIT provisioning improvements and the migration impact.

- [x] [Config to enable JIT provisioning enhanced feature](https://github.com/wso2/product-is/issues/12018)
- [x] [Unique identifier for the JIT provisioned user](https://github.com/wso2/product-is/issues/11991) 
- [x] [Disable editing synced attributes of the JIT provisioned users](https://github.com/wso2/product-is/issues/12010)
- [x] [Introduce userSourceId claim to capture the JIT provisioined source](https://github.com/wso2/product-is/issues/12185)
- [ ] [Option to disable attribute syncing for JIT provisioned users](https://github.com/wso2/product-is/issues/12414)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
