### ISSUE TITLE
Multi Attribute Login Improments / Bugs

### ISSUE THREAD

**Issue by sumedhe** [wso2/product-is#12340]
**Bugs:**

- [x] [Display relevant placeholder when multi-attribute flow is enabled](https://github.com/wso2/product-is/issues/12401)
- [x] [Disable username based login when multi-attribute filtering is enabled and username claim is not configured](https://github.com/wso2/product-is/issues/12437)
- [x] [Support email login without appending carbon.super when email login enabled in multi-attribute login flow](https://github.com/wso2/product-is/issues/12548)
- [ ] [Deprecate the ldap based multi attribute login](https://github.com/wso2/product-is/issues/11784)
- [ ] [Ldap based multi attribute login does not work as expected](https://github.com/wso2/product-is/issues/11783)
- [ ] [Add integration test for multi attribute login feature](https://github.com/wso2/product-is/issues/11530)
- [x] [Add multi attribute login feature to /resend-code api](https://github.com/wso2/product-is/issues/11512)
- [ ] [Multi attribute login - select claim URI from drop-down and validate claim URI](https://github.com/wso2/product-is/issues/11445) **(FE)**
- [ ] [Revisit multi attribute seperator](https://github.com/wso2/product-is/issues/8996)

**Improvements:**
- [x] [A configurable way to set the scope of the claim uniqueness checking](https://github.com/wso2/product-is/issues/12360)
- [x] [Improve the configuration for claim uniqueness checking](https://github.com/wso2/product-is/issues/12472)
- [x] [https://github.com/wso2/product-is/issues/13281](https://github.com/wso2/product-is/issues/13281)

**Doc:**
- [x] Formatting issues in Configuring Uniqueness of Claims docs wso2/docs-is#2758
- [x] [Need a document for multi attribute login feature](https://github.com/wso2/product-is/issues/11504)

**Other related issues:**
- [x] [Support email login without appending tenant domain for non-SaaS apps](https://github.com/wso2/product-is/issues/12601)
- [x] [Support email login without appending tenant domain for Authentication REST API](https://github.com/wso2/product-is/issues/12602)

Related issue: wso2/product-is#8899

**Comment by nilasini** [comment]
https://github.com/wso2/product-is/issues/12815

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
