### ISSUE TITLE
Compatibility issue resolution of STS-Connector 

### ISSUE THREAD

**Issue by minolih** [wso2/product-is#13717]
**Describe the issue:**
STS-Connector (latest from identity-inbound-auth-sts) is not compatible with the IS due to dependency version incompatibilities. 

**Tasks**
- [x]  Upgrade xmlsec in wso2/rampart.
- [x]  Remove log4j package import from opensaml-wso2 and embed reload4j. 
- [x]  Upgrade xmlsec in opensaml-wso2 in orbit repository. 

**How to reproduce:**
Steps to install STS Client and configure WS-Trust Security Token Service. 
Steps to run STS Client - https://is.docs.wso2.com/en/latest/learn/running-an-sts-client/

**Expected behavior:**
1. IS should startup without any errors on the terminal when the STS-Connector is installed to the IS. 
2. IS or STS Client should not give any errors when running the client with the IS and the SAML token issued from STS should be printed by the client.
