### ISSUE TITLE
[Design] Adding the `templateID`'s to the Applications list in Console

### ISSUE THREAD

**Issue by malshan1998** [wso2/product-is#14114]
**Is your suggestion related to an experience ? Please describe.**

The template by which each application is created in the Console's application list, is not displayed. This is important in the aspect of UX. Therefore it should be displayed in the listing.
<img width="1210" alt="Screenshot 2022-07-05 at 14 14 57" src="https://user-images.githubusercontent.com/72730114/177288294-25bca863-d46c-4830-ae89-b5a77465312c.png">

**Describe the improvement**

The `templateID` of each application should be taken from the backend and must be displayed in the listing, either as plain text or a tile/ui-chip item so that later on we can categorize the listing based on template types.

### Tasks

- [ ] Sketch 2 or more design variants 
- [ ] High-level sketch approval
- [ ] Design a high-fidelity design

**Comment by malshan1998** [comment]
The sketch which was approved in the UI/UX review on 06/07/2022 is given below (separate column for template name).
![Final Sketch](https://user-images.githubusercontent.com/72730114/177521891-8be8a867-2163-4f0e-ac90-effe5ca3441b.png)

**Comment by malshan1998** [comment]
This high fidelity design was provided by @kanchanagodage 

![Group 1523 (1)](https://user-images.githubusercontent.com/72730114/183053768-5fddbf7c-6fc0-48f7-885c-39841fca1edd.png)
