### ISSUE TITLE
Session Data Storage Optimization 

### ISSUE THREAD

**Issue by Thananchseyan** [wso2/product-is#14502]
**Is your suggestion related to an experience ? Please describe.**

We are using IDN_AUTH_SESSION_STORE and IDN_AUTH_TEMP_SESSION_STORE for storing caches during the authentication flow. The java objects which are used by the IS are serialized and stored in these tables as BLOB data types. Usually these objects are heavy, so storing and retrieving this data in the database adds load to the database. This leads to major performance bottlenecks in the authentication flow.

**Describe the improvement**

Optimizing the session objects of the session data storage.

- [x] Authentication Context Cache - Optimization #14549 

- [x] Session Context Cache - Optimization #14708 
- [x] Authentication Result Cache - Optimization 
- [x] Authorization Grant Cache - Optimization
- [x] Authentication Request Cache - Optimization 
- [x] Session Data Cache - Optimization 
- [x] Authentication Error Cache - Optimization 
- [x] Long Wait Result Cache - Optimization 
- [x] OIDC session participants Cache - Optimization

Testing 

- [x] Testing with existing data
- [x] Testing by changing the configurations 

Documentation 

- [x] ~~Adding about the Session Data Storage Optimization - Configuration~~ #14722

**Comment by areebniyas** [comment]
After evaluating the caches below it was noticed that they do not hold any bulk objects or attributes that would require an optimization effort:

- Authentication Result Cache
- Authorization Grant Cache
- Authentication Request Cache
- Authentication Error Cache 
- Session Data Cache
- Long Wait Result Cache

**Comment by areebniyas** [comment]
For the OIDC Session Participant Cache, it was noticed that the size of the cache is low. So there wont be a noticeable optimization.

**Comment by senthalan** [comment]
Thank you @Thananchseyan @areebniyas for getting this critical improvement added to the product.
