### ISSUE TITLE
Need an API to obtain the user registration options configured for an application

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#15471]
**Is your suggestion related to an experience? Please describe.**
There can be multiple sign in options configured for an application. All these authenticating options may or may not support signup. There is no way to retrieve only the options that support user registration against a given application.

**Describe the improvement**
Introduce an API to retrieve the user registration supporting authentication options registered for a given application.

**Tasks**

- [x] Core level improvements
- [x] Changes in the API layer
- [x] Integrations tests
- [x] API documentation update
- [ ] Update the UIs to use the new APIs

**Comment by pamodaaw** [comment]
This API improvement should be reverted since the overall architecture of the business user registration is being revamped. There's no impact of removing the newly introduced API since it is not available in any of the released versions of the identity server.

**Comment by pamodaaw** [comment]
A new set of APIs will be introduced to support the signup flow configuration and perform the signup against the configured flow. This requirement will be tracked in the https://github.com/wso2/product-is/issues/16371. Hence closing this issue.
