### ISSUE TITLE
[IS 7.0.0 - Alpha] - New Feature testing and Test case Design 

### ISSUE THREAD

**Issue by melanisilva** [wso2/product-is#16586]
**Task Description**

This Issue will track all the Feature testing tasks that will be carried out with the new features in the IS 7.0.0 - Alpha milestone.

### Optional Fields

**Feature List**

- [x] #16013 
- [x]  [HYPR Federated Authentication ](https://github.com/wso2/product-is/issues/15361)
- [x]  [Make Identity Server FIPS compliant](https://github.com/wso2/product-is/issues/15428)
- [x]  [Providing CLI to propagate configurations across environments #15461](https://github.com/wso2/product-is/issues/15461)
- [x] [Email OTP-based user authentication (first factor) #15581](https://github.com/wso2/product-is/issues/15581)

**Related Issues:**

**Comment by melanisilva** [comment]
### Update - Improvement to PAR Implementation - 04th SEP 2023

- [ ] Go through the [OAuth 2.0 Pushed Authorization Requests](https://datatracker.ietf.org/doc/html/rfc9126) spec. - Inprogress
- [ ] Create test plan - In progress
- [ ]  Conduct the Feature testing
