### ISSUE TITLE
SCIM custom schema URI configured from charon-config.xml is not adhered in UI 

### ISSUE THREAD

**Issue by AnuradhaSK** [wso2/product-is#16916]
**Describe the issue:**

1. As mentioned here 
https://is.docs.wso2.com/en/latest/references/extend/provisioning/add-scim2-custom-user-schema-support/#add-custom-schema-dialect:~:text=If%20you%20want%20to%20change%20the%20name%20of%20the%20schema%2C%20you%20can%20add%20the%20configuration%20given%20below%20to%20the%20%3CIS_HOME%3E/repository/conf/identity/charon%2Dconfig.xml%20file.

Open `<IS_HOME>/repository/conf/identity/charon-config.xml` file and change the `custom-user-schema-uri` value
`<Property name="custom-user-schema-uri">urn:scim:custom:schema:new</Property>`

2. Then Go to Console application -> Attributes section. Click on attributes tile and try to add new attribute with scim claim mapping
3. It will take the IS default scim custom schema not the configured value in the file.
<img width="781" alt="Screenshot 2023-10-10 at 23 41 51" src="https://github.com/wso2/product-is/assets/25483865/c78f636d-64ae-44bb-af77-defa99c4f9ab">

**Expected behavior:**
Custom schema URI shown in the UI should be updated according to server level configured value

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version:  7.0.0-m4-SNAPSHOT

**Comment by DilshanSenarath** [comment]
At present, reading the charon-config.xml is not possible in the frontend, even when the custom URI name is modified it is not accessible. Therefore, currently it is hardcoded (`urn:scim:wso2:schema:`) on the console side. Therefore, we need to determine and finalize an approach to address this issue. The resolution of this matter will remain on hold until the approach is decided upon.

**Comment by mpmadhavig** [comment]
**Task List:**

- [ ] Create `charon-config.xml.j2` using `charon-config.xml`.
- [ ] Add config default values to `default.json`.
- [ ] Add logic to read the custom schema name from config file.
- [ ] Add documentation mentioning about the data migration.
    - Already created custom attributes under the old dialect name should be migrated to the new dialect.
    - When console is externally hosted, add the config to the `deployment.config.json`
