### ISSUE TITLE
UX enhancements for the Applications section

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#17917]
# Task List
### Application Listing
- [x] Should improve the list view (Separate myaccount from list view and hide the console) (@DilshanSenarath)

### My Account (@DilshanSenarath )
- [x] should be sharable to other orgs
- [x] sign-in method should be editable
- [x] support externalizing the myaccount
- [x] attribute sharing should be editable
- [x] Evaluate the use cases (https://github.com/wso2/product-is/issues/17665)

### Console (@brionmario) (Tracked Separately: https://github.com/wso2/product-is/issues/16709)
- should be listed as a separate settings section
- editable section
  - sign-in methods
  - addition of roles
  - externalizing the console

#### Traditional Web Application
- [x] Remove sample app url add message
