### ISSUE TITLE
Fix the connections related bugs

### ISSUE THREAD

**Issue by DilshanSenarath** [wso2/product-is#18028]
# Task List
### Sign In Method
- [x] Add authenticator wizard
  - [x] Fix the expert mode logo issue
  - [x] Fix the enterprise idp logo issue
  - [x] Fix the trusted token idp logo issue
  - [x] Every connection create from this section doesn't have a proper logo url
  - [x] Configure New Connection
    - [x] Cards are too large 
    - [x] Remove linkedln
    - [x] Remove Organization SSO
    - [x] Custom connector is not working
    - [x] Sign in ethereum is not working
    - [x] trusted token should be removed in IS
- [x] Added custom authenticators should be visible after adding an authenticator (This is working after going to the settings page again and come to add wizard)

### Connections
- [x] Disable trusted token in IS
- [x] Custom connection (Expert mode)
  - [x] Github image is missing
