### ISSUE TITLE
Move HYPR connector resource files to the store

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#18416]
**Describe the issue:**
We are required to relocate the HYPR IDP-related resource files to the Connector Store. This involves removing the templates from the carbon framework [1] and establishing them as an artifact within the Connector Store.

### Task Breakdown

- [ ] Update the HYPR connector store artifact including the UI resource files.
- [ ] Remove the resource files from [1] and update the hidden connections related configuration as below.

```
"console.ui.hiddenConnectionTemplates": [ "swe-idp" ]
```

- [ ] Revise connector and public documentation to reflect the new location of HYPR IDP templates in the Connector Store.

[1] - https://github.com/wso2/carbon-identity-framework/tree/master/features/extension-mgt/org.wso2.carbon.identity.extension.mgt.feature/resources/extensions/connections/hypr
[2] - https://github.com/wso2/carbon-identity-framework/blob/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/org.wso2.carbon.identity.core.server.feature.default.json#L1049
