### ISSUE TITLE
Testing IAM Access Delegation Scenarios in WSO2 Identity Server 7.0.0

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#19360]
**Is your suggestion a test requirement/change or improvements of the test framework? Please describe.**
Validating IAM access delegation scenarios in WSO2 Identity Server 7.0.0, and  requested to perform testing on the following sub-categories:

**Describe the solution you would prefer**

- [ ] [OAuth 2.0 Grant Types ](https://github.com/wso2/product-is/issues/19364)

- [x] Microprofile JWT - https://github.com/wso2/product-is/issues/19364 

- [ ] [SAML2 Bearer Assertion Profile](https://is.docs.wso2.com/en/latest/guides/access-delegation/saml2-bearer-assertion-profile/)

- [ ] [Kerberos](https://is.docs.wso2.com/en/latest/guides/access-delegation/configure-kerberos-grant/)

- [ ] [JWT Grant](https://is.docs.wso2.com/en/latest/guides/access-delegation/configure-jwt-grant/)

- [ ] [OAuth 2.0 Introspection](https://is.docs.wso2.com/en/latest/guides/access-delegation/invoke-oauth-introspection-endpoint/)

- [ ] [OAuth 2.0 Dynamic Client Registration](https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-dynamic-client-registration/)

- [ ] [OAuth 2.0 Client Authentication](https://is.docs.wso2.com/en/latest/guides/access-delegation/private-key-jwt-client-authentication-for-oidc/)

- [x] OAuth 2.0 Transaction Logs https://github.com/wso2/product-is/issues/19365

- [x] OAuth 2.0 Token Hashing https://github.com/wso2/product-is/issues/19368

- [ ] [Revoke OAuth Tokens](https://is.docs.wso2.com/en/latest/guides/access-delegation/oauth-token-revocation/)

- [ ] [Mutual TLS for OAuth clients](https://is.docs.wso2.com/en/latest/guides/access-delegation/mutual-tls-for-oauth-clients/) https://github.com/wso2/product-is/issues/19675

- [ ] Validate documentations 

Confirm the availability and accuracy of documentation related to IAM access delegation in WSO2 IS 7.0.0.
Check for the latest documentation and report any discrepancies or missing information.

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by aaujayasena** [comment]
Documentation issues:
- https://github.com/wso2/product-is/issues/19305
- https://github.com/wso2/product-is/issues/19296
-

**Comment by aaujayasena** [comment]
Product issues:
