### ISSUE TITLE
Support to selectively enable or disable login access to applications.

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#20378]
**Is your feature request related to a problem? Please describe.**
In CIAM solutions, there's a need to selectively disable application access for users for various reasons, like security concerns or compliance requirements. Currently, Identity server do not has this support. 

**Describe the solution you would prefer**
Add support to selectively enable and disable application login access through Application Mgt API

**Phase 1**
- [x] BackEnd and API capability to enable/disable user login/access for an application
- [x] Administrative UI in the Console to enable/disable Myaccount at the organization level

**Phase 2**
- [x] Consent and active token revocation while disabling the access

**Comment by VivekVinushanth** [comment]
Being supported with
- https://github.com/wso2/identity-api-server/pull/612

**Comment by VivekVinushanth** [comment]
This introduces a change to the application mgt APIs and hence require documentation update.

**Comment by VivekVinushanth** [comment]
Phase 2:
**Revoke consents**
- https://github.com/wso2/carbon-identity-framework/pull/5732

**Comment by VivekVinushanth** [comment]
**Doc update**
- [ ] #20387

**Comment by VivekVinushanth** [comment]
Improvement suggestions
- [ ] https://github.com/wso2/product-is/issues/21258
- [ ]
