### ISSUE TITLE
Support for Pre Issue Access Token network extension

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#20739]
**Is your feature request related to a problem? Please describe.**
As of now in order to extend the pre issue access token flow, users have to extend Java SPIs in the product in multiple places.
This makes it hard to manage and maintain as product internal architecture and data is exposed to the extension. TCO of such an extended deployment is high.

**Describe the solution you would prefer**
This feature is intended to provide support to invoke an external service registered just before issuing access tokens to allow any edits to access token claims like validity period, add or update scopes, add or update any additional claims.
The product should define a contract defined for this flow that the service that extends need to implement.

**Implementation Tasks:**

- [x] [Implement action execution core component ](https://github.com/wso2/carbon-identity-framework/pull/5810)
- [x] [Implement pre issue access token action invocation at oauth component (changes to JWT access token only in password, authorization code, client credentials and refresh grant)](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2528)
- [x] Cover unit tests for action execution core component
- [x] Cover unit tests for pre issue access token action invocation
- [x] [Have facility to enable or disable execution of pre issue access token actions at server level](https://github.com/wso2/product-is/issues/20927)
- [x] [Support configuring headers and params to exclude in action request in server level](https://github.com/wso2/product-is/issues/20926)
- [ ] [Improve diagnostic logs associated with the action ](https://github.com/wso2/product-is/issues/21210)
- [ ] Improve pre issue access token action to perform modifications for refresh token validity
- [ ] Extend pre issue access token action to be invoked at token exchange grant
- [x] [Cover integration tests for pre issue access token action](https://github.com/wso2/product-is/issues/20842)
- [x] [Improve to configure action execution related timeouts, retry counts in server level](https://github.com/wso2/product-is/issues/21119)
- [x] Implement and e2e test for the pre issue access token action
- [x] [Add documentation for pre issue access token](https://github.com/wso2/product-is/issues/20897)

**Comment by malithie** [comment]
This is completed for Identity Server
