### ISSUE TITLE
Implement action management to configure and manage external endpoints invoked synchronously in product flows

### ISSUE THREAD

**Issue by ashanthamara** [wso2/product-is#20747]
### **Is your feature request related to a problem? Please describe.**
When it comes to IS, Asgardeo and PIC we don’t have the capability to orchestrate the flow or update system state based on a custom logic that may or may not integrate with various business systems synchronously. So if a customer wants to customize their certain flows as we are doing in adaptive scripts, there is no way we can provide that capability through our product.

### **Describe the solution you would prefer**
In order to provide this capability we should first allow the users to configure external endpoints under certain action types in the product.  And for that we need to have set of Management APIs and a relevant section in the console UI to visualize them.

### **Implementation Tasks:**

- [x] Add Action Management Rest APIs https://github.com/wso2/product-is/issues/20748
    - https://github.com/wso2/carbon-identity-framework/pull/5771
    - https://github.com/wso2/identity-api-server/pull/626
    - https://github.com/wso2/product-is/pull/20634
- [x] Secure the secrets in Action Management component. https://github.com/wso2/product-is/issues/20750 
    - https://github.com/wso2/carbon-identity-framework/pull/5795
    - https://github.com/wso2/identity-api-server/pull/630
    - https://github.com/wso2/product-is/pull/20706
    - https://github.com/wso2/carbon-identity-framework/pull/5808
    - https://github.com/wso2/identity-api-server/pull/635
    - https://github.com/wso2/product-is/pull/20736
- [x] Add UI for the Action Configuration https://github.com/wso2/product-is/issues/20751
- [x] Add Unit tests of the action-mgt component https://github.com/wso2/product-is/issues/20752
- [x] Update migration client to reflect schema changes https://github.com/wso2/product-is/issues/21172#issue-2550158726
- [ ] Add Audit Logs
- [x] Docs
    - https://github.com/wso2/docs-is/pull/4700

**Comment by ashanthamara** [comment]
Closing as this is completed
