### ISSUE TITLE
Support for external custom authention extension

### ISSUE THREAD

**Issue by Thisara-Welmilla** [wso2/product-is#20809]
**Is your feature request related to a problem? Please describe.**

Considering IS, Asgardeo, and PIC, it's a common requirement to have a capability to authenticate users with a custom authenticator that we do not provide out of the box. Currently:
For IS, the IAM developer must create an authenticator extension and add it as a binary to the product and for Asgardeo, there is no way to accomplish this.

**Describe the solution you would prefer**

This feature is intended to provide support for user authentication via an external custom authentication service. Such authenticator can be added to application login flow.
The product should define a contract defined for this flow that the service that extends need to implement.

**Implementation Tasks:**

- [x] Support configuring the external authenticator properties with action feature /issues/20931
- [x] Bring in prepost and inflow action separation action management so that custom authenticator can be considered as inflow action /issues/21384
- [x] Custom authenticator adapter for user authentication with external service  /issues/20887
- [x] Introduce new authenticator properties: DefinedBy to indicate whether authenticator is SYSTEM or User Defined /issues/21111
- [x] Provide support for the new cutsom authentication management /issues/21216
- [x] Improve UI to incorporate authentication flow with the external authentication service /issues/20893
- [ ] Implement and e2e test for the new authenticator usages
- [ ] Documentation on external authentication service /issues/21036
