### ISSUE TITLE
[Test] [Feature] Multi-Tenancy capabilities

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-is#22005]
### Description

Required to test app-wise branding feature.

Relates issue: https://github.com/wso2/product-is/issues/21178

**Task Breakdown** 

- [ ] Verify the documentation
- [ ] Verify the migration reediness
- [ ] Verify test cases
- [ ] Verify feature scenario

**Comment by aaujayasena** [comment]
**Verify the documentation**

1. Documentation availability - Pass
2. Improvement reported:  https://github.com/wso2/product-is/issues/22004

**Comment by aaujayasena** [comment]
**Verify the migration reediness**

**Comment by brionmario** [comment]
> **Verify the migration reediness**

This is a new feature for the Console and the already created tenants for migrating customers will automatically work.

**Comment by aaujayasena** [comment]
> > **Verify the migration reediness**
> 
> This is a new feature for the Console and the already created tenants for migrating customers will automatically work.

@brionmario Did we test and verified this.

**Comment by aaujayasena** [comment]
This is completed. Hence closing the issue
