### ISSUE TITLE
TO-DO For CIBA  Feature

### ISSUE THREAD

**Issue by VivekVinushanth** [wso2/product-is#7022]
* CIBA **core feature** was implemented with relevance to the specification.

**To-do**
---
- [ ] Make polling **interval** and default **expiry_time** configurable.
- [ ] Add signature verification.
- [ ] Support '**ping**' as a token request mode.
- [ ] Need new decoupled authenticator [that can also retrieve parameters like **binding_message** and **transaction_context**  from parameterMap of request.]
- [ ] Support for **user_code**.
- [ ] Need to add the grant type and expose the ciba endpoint in identity.xml
- [ ] Create a new feature for the ciba bundle
- [ ] Be FAPI CIBA profile compliant (https://openid.net/specs/openid-financial-api-ciba-ID1.html)
- [ ] Be CIBA profile compliant

Also refers: https://github.com/wso2/product-is/issues/6835

**Comment by senthalan** [comment]
7. Need to add the grant type and expose the ciba endpoint in identity.xml
8. Create a new feature for the ciba bund;e

**Comment by janakamarasena** [comment]
9. Create a Sample app demonstrating CIBA capabilities

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
