### ISSUE TITLE
Provide capability to encrypt internal sensitive data with symmetric encryption

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#7898]
**Terms:**

- Symmetric encryption is an encryption approach which uses a shared secret key for both encryption and decryption of data.

**Description:**
In current WSO2 IS distributions, it supports asymmetric encryption by default for encrypting internal data of the identity server. 
With this new improvement, the WSO2 IS product will have symmetric encryption as the default encryption approach for encrypting internal data
Example of internal data:

1. Oauth tokens, client secrets, authorization codes
2. Secondary userstore password.

**Tasks:**
- [x] Fix CryptoUtil component to support symmetric encryption - https://github.com/wso2/product-is/issues/7903
- [x] Fix Crypto Service component to support symmetric encryption - https://github.com/wso2/product-is/issues/7904
- [x] Fix user store management component to support symmetric encryption - https://github.com/wso2/product-is/issues/7905
- [x] Enable the symmetric encryption configuration to be packed by default in WSO2 IS - https://github.com/wso2/product-is/issues/7906
- [x] Update documentation - https://github.com/wso2/product-is/issues/7907
- [x]  Add integration tests - https://github.com/wso2/product-is/issues/7908
- [x] Add migration tool for symmetric encryption support - https://github.com/wso2/product-is/issues/7910

**Comment by pulasthi7** [comment]
Closing as all the subtask features are completed
