### ISSUE TITLE
Tenant-qualify URLs in metadata documents

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7901]
**Description:**

In WSO2 identity server, there is a requirement to make all the endpoints tenant-qualified. Hence, the existing metadata endpoints along with the metadata URLs of these documents should be made to comply with that. The tenant qualified URL pattern should take the form '/t/{tenant.domain}'.

The identified tasks for the above requirement as follows.

**Tasks:**

- [x] 1. Provide tenant-qualified URL support for SAML metadata endpoint - #7900 

- [x] 2. Provide tenant-qualified URL support for OIDC discovery endpoint. #7932 

- [x] 3. Provide tenant-qualified URL support for Server metadata (Resident IdP). #7931

**Comment by malithie** [comment]
Fixed
