### ISSUE TITLE
Qualify WSO2 Identity Server endpoints with tenant in path - (phase 01)

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7902]
**Description:**

In WSO2 Identity Server, there is a requirement to make all the endpoints tenant qualified. The tenant qualified URL pattern for the endpoints should take the form '/t/{tenant.domain}'.
Eg:  localhost:9443/t/{tenant.domain}/scim2/users

Currently, apart from the rest APIs, almost all the other endpoints are having the same endpoint for all the tenants. 
Eg: localhost:9443/commonauth

A few endpoints are tenant-qualified by appending the tenant domain as a query parameter to the URLs whereas some are tenant-qualified by appending the tenant domain as a path parameter to the URLs.

With this feature enabled, all the URLs would have the tenant domain as a path parameter as described above. If the inbound/outbound traffic in the identity server can be made tenant-qualified, it would pave the way for a bunch of new improvements and features.

**Tasks:**

The following are the main tasks that has been identified for the first phase of this feature.
- [x] [Add a utility to construct service urls of the server](https://github.com/wso2/product-is/issues/8194)

- [x] [Tenant-qualify Core Inbound paths to the server](https://github.com/wso2/product-is/issues/7922) 

- [x] [Tenant-qualify Core Outbound paths](https://github.com/wso2/product-is/issues/7923)

- [x] [Tenant-qualify URLs metadata documents](https://github.com/wso2/product-is/issues/7901)

- [x] [Allow access to super tenant from server base context](https://github.com/wso2/product-is/issues/8144)

- [x] [Restrict access to super tenant with carbon.super in path param](https://github.com/wso2/product-is/issues/8328)

- [x] [Cover integration and unit tests for non tenant qualified url mode](https://github.com/wso2/product-is/issues/8524)

- [ ] [Track migration impact for tenant qualified URL](https://github.com/wso2/product-is/issues/9068)

**Comment by Buddhimah** [comment]
Content Related to migration tracked and added to gdoc.
