### ISSUE TITLE
Add migration tool for symmetric encryption

### ISSUE THREAD

**Issue by denuwanthi** [wso2/product-is#7910]
**Description:**

When migrating from an old version to latest version, if the old version is using asymmetric encryption to encrypt internal data, we need to provide a migration tool to convert those data to symmetric encryption.

- [x] [Introduce new API to pass the preferred internal crypto provider type to crypto service](https://github.com/wso2/product-is/issues/8148).

- [x] [Add migration client and sync client](https://github.com/wso2/product-is/issues/8384)
- [x] [Test migration client and sync client](https://github.com/wso2/product-is/issues/9275)
