### ISSUE TITLE
Provide Unique ID support for groups

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#7912]
**Terms:**

- A set of new Group APIs should be introduced in order to support this.

**Description:**

At the moment IS does not support retrieving existing groups of a user store through SCIM support. Hence this feature should provide flexibility to plug any user store with groups with or without group-id.

Also, this will not be an alternative to current role architecture. Permissions and hybrid roles will not be considered for this Group API. This API will be used to handle the grouping concept.  

**Tasks:**

- [x] Finalizing interfaces for the unique group ID feature: https://github.com/wso2/product-is/issues/7365
- [x] AD and LDAP implementation for unique id for groups: https://github.com/wso2/product-is/issues/7913
- [x] JDBC implementation for unique id for groups: https://github.com/wso2/product-is/issues/7914
- [x] Integrate the user core group implementation with SCIM 2.0: https://github.com/wso2/product-is/issues/7915

**Comment by somindatommy** [comment]
This is fixed and will be available with IS 7.0.0.
