### ISSUE TITLE
Tenant-qualify Inbound paths to the server

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#7922]
**Description:**

As per the feature to make all the endpoints tenant-qualified, the existing inbound paths to the identity server should be qualified to have the tenant domain in path. The tenant-qualified URL pattern should take the form '/t/{tenant.domain}'.

The identified tasks for the above requirement are as follows.

Tasks:

- [x] 1. Tenant-qualify inbound paths of Carbon webapps. #7924 

- [x] 2. Tenant-qualify inbound paths of CXF webapps. #7925 

- [x] 3. Tenant-qualify inbound paths of JSP-based webapps. (Captures core webapps only; authentication endpoint and recovery endpoint) #7927
