### ISSUE TITLE
Tenant-qualify outbound paths 

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#7923]
**Description:**

As per the feature to make all the endpoints tenant-qualified, the existing outbound paths from the identity server and redirects should be qualified to have the tenant domain in path. The tenant-qualified URL pattern should take the form '/t/{tenant.domain}/*'.

The identified tasks for the above requirement are as follows.

Tasks:

- [x]  Tenant qualify outbound paths of Carbon Web apps. [#7929](https://github.com/wso2/product-is/issues/7929)
- [ ]  Tenant qualify outbound paths of CXF web apps. [#7930](https://github.com/wso2/product-is/issues/7930)
- [x]  Tenant qualify outbound paths of JSP-based web apps. [#7928](https://github.com/wso2/product-is/issues/7928)

**Comment by ayshsandu** [comment]
captured in https://github.com/wso2/product-is/issues/9051
