### ISSUE TITLE
Tenant-qualify outbound paths of CXF Webapps

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#7930]
Description:
The current outbound paths from CXF web apps do not have the tenant domain as a path parameter.
This task will tenant-qualify the outbound paths (redirects, response content) by appending the tenant domain as follows,
eg: localhost:9443/t/{tenant.domain}/oauth2/...

This task will tenant-qualify the following CXF webapp endpoints,

- [x] /oauth2 : https://github.com/wso2/product-is/issues/8156
- [x] /scim2/ : https://github.com/wso2/product-is/issues/8404
- [x] /api/server/* : https://github.com/wso2/product-is/issues/8208
- [x] /api/user/* : https://github.com/wso2/product-is/issues/8296
- [x] /identity/api/config https://github.com/wso2/product-is/issues/8545
- [x] /identity/oauth2/dcr https://github.com/wso2/product-is/issues/8616
- [x] /identity/oauth2/uma https://github.com/wso2/product-is/issues/8625
- [x] /identity https://github.com/wso2/product-is/issues/8626
