### ISSUE TITLE
Tenant qualify URLs of the Authentication Endpoint JSP web app

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#7993]
**Description:**
The current inbound/outbound paths of the Authentication Endpoint webapps do not have the tenant domain as a path parameter. This task will tenant-qualify the inbound and outbound paths by appending the tenant domain as follows,
eg: localhost:9443/t/{tenant.domain}/authenticationendpoint/...

The implementation of this feature consists of the following tasks,
- [x] Allow webapps to be accessed in normal tenant context: https://github.com/wso2/product-is/issues/7998
- [x] Tenant qualifying inbound paths to the Authentication endpoint: https://github.com/wso2/product-is/issues/8031
- [x] Tenant qualifying outbound paths from the Authentication endpoint: https://github.com/wso2/product-is/issues/8027
- [x]  Rewriting URLs with tenant contexts for internal processing: https://github.com/wso2/product-is/issues/8026
- [x] Enabling the webapp to capture and apply filters to dispatcher forwards made internally: https://github.com/wso2/product-is/issues/8001

**Comment by malithie** [comment]
Done
