### ISSUE TITLE
Windows Desktop sample and .Net Authentication SDK

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8103]
**Problem description**
As of now, Identity Server has full server side capabilities to secure windows desktop applications. Yet, it don't have any client side tools like SDKs or official guides on how to integrate desktop application with IS.

Having a official SDKs, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on
- Selecting and applying best practices on different authentication protocols
- Selecting correct libraries to implement
- Make that client side implementation to integrated with IS

etc.

**Preferred Solution**
Have .Net Authentication SDK, Windows Desktop sample and needed guides to make desktop app integration with Identity Server very simple.

**Sub Tasks**
- [x] [.NET Standard SDK for IS](https://github.com/wso2/product-is/issues/8106)
- [x] [Windows Desktop (WPF) sample for IS using .NET SDK](https://github.com/wso2/product-is/issues/8107)
- [x] [Windows Desktop App Template](https://github.com/wso2/product-is/issues/8108)
- [x] [Dev-Portal side panels for .NET Samples\SDKs for Windoes Desktop App type](https://github.com/wso2/product-is/issues/8109)
- [x] [.NET SDK Developer documentation](https://github.com/wso2/product-is/issues/8112)
- [x] [WPF Sample Doumentation](https://github.com/wso2/product-is/issues/8105)

Following improvements are captured in https://github.com/wso2/product-is/issues/10818,

- [UX improvements for Windows (WPF) sample](https://github.com/wso2/product-is/issues/8104)
- [Have side panal to show the personalized resouce file (installer conf)](https://github.com/wso2/product-is/issues/8110)
- [Improve the installer to point a a resouce file](https://github.com/wso2/product-is/issues/8111)
Effort BE::34
