### ISSUE TITLE
Provide separate SCIM 2.0 Group and Role APIs

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#8123]
**Terms:**

A clear separation of Group and Role APIs should be implemented in the SCIM 2.0.

**Description:**

To provide a group and role APIs separately via SCIM 2.0 along with the separated group and role concepts by utilizing the existing user core APIs. This will be implemented based on identity cloud requirements.

- **Group:** A representation of a set of users (current hybrid roles should not be included)
- **Role:** Roles within IAM solution. That binds with permissions defined for resources within the IAM solution. This can be mapped to present hybrid roles

**Tasks:**
- [x] Implement role management service: https://github.com/wso2/product-is/issues/8373
- [x] Implement SCIM 2.0 Role API: https://github.com/wso2/product-is/issues/8591
- [x] Modify the AuthorizationManager and other usercore components: https://github.com/wso2/product-is/issues/9040
- [x] Add role and group separation changes to SCIM 2.0 users and groups endpoints: https://github.com/wso2/product-is/issues/9178
- [x] Provide Roles support in SCIM2 /Bulk endpoint: https://github.com/wso2/product-is/issues/9233
- [x] Add the integration tests for SCIM 2.0 Roles endpoint: https://github.com/wso2/product-is/issues/9054
- [x] Add the documentation for SCIM 2.0 Roles API: https://github.com/wso2/product-is/issues/9064
- [x] Implement the migration strategy: https://github.com/wso2/product-is/issues/9041 
- [x] Make group and role separation enabled by default in the product: https://github.com/wso2/product-is/issues/9494
