### ISSUE TITLE
Java Webapp sample & Spingboot Extension

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8252]
**Problem description**
As of now, Identity Server has full server side capabilities to secure web applications. Yet, it have limited client side tools like SDKs or official guides on make use off security components on different web app frameworks to integrate with IS.

Spring is a popular application framework and have inbuilt mechanisms secure an web application. Having a official samples and guides will make the developer experience more convenient.

**Preferred Solution**
Have Spring sample and needed guides to make web app integration with Identity Server very simple.

**Sub Tasks**
- [x] [Authentication Extension for Spring Boot Applications](https://github.com/wso2/product-is/issues/8261)
- [x] [Sample using authentication extesion for Spring Boot](https://github.com/wso2/product-is/issues/8260)
- [x] [Developer documentation for Spring Boot extension](https://github.com/wso2/product-is/issues/8259)
- [x] [Sample documentation for Spring Boot extension](https://github.com/wso2/product-is/issues/8258)
- [x] [Spring Boot App Template](https://github.com/wso2/product-is/issues/8257)
- [x] [Dev-Portal side panals for Spring Boot Apps](https://github.com/wso2/product-is/issues/8256)
- [ ] [Have side panal to show the personalized resouce file (Springboot conf)](https://github.com/wso2/product-is/issues/8255)
- [ ] [UX improvements for Springboot sample](https://github.com/wso2/product-is/issues/8254)
- [ ] [IDE plugin to generate the project template](https://github.com/wso2/product-is/issues/8253)

Effort BE::34

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
