### ISSUE TITLE
Mobile authentication sample and Android SDK

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8263]
**Problem description**
As of now, Identity Server has full server side capabilities to secure mobile applications. Yet, it don't have any client side tools like SDKs or official guides on how to integrate mobile application with IS.

Having a official SDKs, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on
- Selecting and applying best practices on different authentication protocols
- Selecting correct libraries to implement
- Make that client side implementation to integrated with IS

etc.

**Preferred Solution**
Having Android SDK, Android mobile sample and needed guides makes mobile app integration with Identity Server very simple.

**Additional context**
As a additional context, the SDK should provide the capabilities to get information related to protocol information like tokenresponse, idtoken and userinfo calls. 
The android-sample should have the code blocks to show these capabilities of SDK.
All the SDK related APIs need to be documented since android-sample can't showcase all the capabilities of the SDK

**Sub Tasks**
- [x] [Android SDK mobile apps](https://github.com/wso2/product-is/issues/8269)
- [x] [Android SDK sample for IS](https://github.com/wso2/product-is/issues/8268)
- [x] [Developer documentation for Android SDK](https://github.com/wso2/product-is/issues/8267)
- [x] [Sample Documentation for Android Sample](https://github.com/wso2/product-is/issues/8266)
- [x] [Android SDK App Template](https://github.com/wso2/product-is/issues/8265)
- [x] [Dev portal side panels for Android SDK](https://github.com/wso2/product-is/issues/8264)

**Comment by piraveena** [comment]
Refer the [Android-SDK](https://github.com/wso2-extensions/identity-sdks-android) and [Android-sample](https://github.com/wso2-extensions/identity-samples-android)

**Comment by darshanasbg** [comment]
Duplicates https://github.com/wso2/product-is/issues/8263
