### ISSUE TITLE
JavaScript Authentication (OIDC) SDKs & Samples

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8270]
**Problem description**
As of now, Identity Server has full server-side capabilities to secure SPAs. Yet, it doesn't have any client-side tools like SDKs or official guides on how to integrate SPAs with IS.

Having an official SDK, samples and guides will make the developer experience more convenient. This will help the app developer to avoid spending time on
- Selecting and applying best practices on OIDC authentication protocol
- Selecting correct libraries to implement
- Make that client-side implementation to integrated with IS

etc ...

**Preferred Solution**
Develop a core JS SDK and develop wrappers using it to React, React Native, Angular, Vue etc ...
And create samples to demonstrate usage. Also, developer guides on the usages.

Effort FE::40

**Sub Tasks**
- [x] [Javascript Authentication (OIDC) SDK for IS](https://github.com/wso2/product-is/issues/8271)
- [x] [Developer Documentation for Javascript SDK](https://github.com/wso2/product-is/issues/8273)
- [x] Simple webpage/webapp sample for demonstrate JS SDK UMD (Browser) version usage
- [x] [A sample app for demonstrate JS SDK NPM module Javascript usage](https://github.com/wso2/product-is/issues/8274)
- [x] Improve the javascript sample and move to asgardio org.
- [x] A sample for demonstrate JS SDK NPM module Typescript usage
- [x] Improve typescript sample
- [ ] Unit tests
- [ ] Cypress/Integration Tests
- [x] JS App Template
- [ ] Dev portal side panels for JS SDK
- [x] Add OIDC validations to the SDK
- [x] [Add extended functionalities to JavaScript SDK](https://github.com/wso2/product-is/issues/9100)
- [x] [Use rollup to bundle the SDK](https://github.com/wso2/product-is/issues/10554)
- [x] [Add FIDP feature to the SDK](https://github.com/wso2/product-is/issues/10555)

**Comment by thivi** [comment]
Tasks completed by https://github.com/asgardeo/asgardeo-js-oidc-sdk/pull/95
