### ISSUE TITLE
Git Integration for Service Provider definitions in WSO2 Identity Server

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2/product-is#8278]
**Problem definition**
Current way of introducing an update of the Service Provider, or adding new service provider to a particular environment is by doing that change manually through the management console.

This is an error prone approach and make the configuration changes propagated through environments.

**Preferred Solution**
Having Identity Server capable of pulling Service Provider artifacts through its representation stored in a VCS like Github solve this. This will allow to automate configuration changes automatically propagated through different environments, with correct CI\CD pipelines and test suits in place.

Retrieving the configuration updates can be done with both pull (periodic pulling), and push (with GitHub Webhook) models.

**Tasks**
- [x] [Remote fetch support for IS](https://github.com/wso2/product-is/issues/8279)
- [x] [VS Code extension to pull/push SPs](https://github.com/wso2/product-is/issues/8280)
- [x] [VS code language server support to build adaptive authentication scripts](https://github.com/wso2/product-is/issues/8281)
- [x] [Rest API for remote fetch service](https://github.com/wso2/product-is/issues/8282)
- [x] [Add support for git hooks for GIT integration](https://github.com/wso2/product-is/issues/8283)
- [x] [Add GIT integration UI to the developer portal](https://github.com/wso2/product-is/issues/8284)
- [ ]  Permission and Scope creation for Rest end points.
- [ ]  Integration Test with product IS.

**Comment by Thumimku** [comment]
Implementation of Web hook Action Listener
https://github.com/wso2-extensions/identity-fetch-remote/pull/34

**Comment by pulasthi7** [comment]
@DimalChandrasiri @JKAUSHALYA Can we close this issue now?

**Comment by DimalChandrasiri** [comment]
Closing this issue since Fixed by this [PR](https://github.com/wso2/identity-apps/pull/1264). The incomplete tasks will be tracked in this new [issue.](https://github.com/wso2/product-is/issues/10283)
