### ISSUE TITLE
Allow CORS configuration at tenant level

### ISSUE THREAD

**Issue by ivantha** [wso2/product-is#8337]
**Description:**

Currently, the Identity Server allows the CORS to be configured at the server level in the repository/resources/conf/templates/repository/conf/tomcat/web.xml.j2. It is required that the CORS are allowed to be configured at the tenant level.

This feature will only be implemented for the new tenant qualified URL mode of the IS as it is infeasible to identify the tenant for some of the existing endpoints by only using the request URL. 

**Design decisions:**

- The enforcement of the CORS was decided to be done at the tenant level as app-level enforcement would require unique URLs per app.

- The CORS will be allowed to be configured during the application creation to improve the UX. When a CORS origin is added to the IS at the tenant level, it will have an association with one or more applications. 

**Scenario:**
![use_case (1)](https://user-images.githubusercontent.com/14804283/88940450-5ffbdd80-d2a5-11ea-89b3-d966dc16a899.png)

**Architecture:**
![architecture](https://user-images.githubusercontent.com/14804283/88940217-24611380-d2a5-11ea-83aa-bee65aa21d70.png)

**Tasks:**

The following subtasks have been identified in order to $subject. 

- [x] Design a Tomcat Valve to write CORS headers on requests. - #8551

- [x] Handle the tenant-wise CORS related functionality through an OSGi service. - #8348

- [x] Implement a REST-API for the tenant admins to manage CORS configurations. - #8550

- [x] Implement a REST-API for the developers to manage CORS of applications. - #8877 

- [x] Implement a REST-API for CORS origin management. - #9047 

- [x] Introduce a table for the CORS following the Dao pattern. - #9065

- [x] Integrate CORS components to the product-is. - #9066

- [x] Write integration tests for the REST APIs. - #9222

- [x] Add the documentation for CORS. - #9067
