### ISSUE TITLE
Media Service API

### ISSUE THREAD

**Issue by dewniMW** [wso2/product-is#8499]
**Description:**

The Image Service API [1] is designed to provide the capability to upload an image to user profile, service provider and identity provider in WSO2 Identity Server. As the next phase, the Image Service API will be generalized as Media Service API so as to give the flexibility to perform file uploads and downloads of different types.

**Phase 01 - Tasks:**

The following subtasks have been identified for $subject. 

- [x] Design and implement REST API. 

- [x] Improve the existing image service [2] to support media service related functionalities.

- [x] Implement JAX-RS security filter for media download and management operations. https://github.com/wso2/product-is/issues/8582

- [x] Introduce media service related configurations in identity.xml. https://github.com/wso2/product-is/issues/8543

- [x] Add media management permissions to the permission tree. https://github.com/wso2/product-is/issues/8542

- [x] Add support for scope-based API authorization. https://github.com/wso2/product-is/issues/8631

- [x] Add unit tests.

- [ ]  Add configuration to enable Media Service. https://github.com/wso2/product-is/issues/9057

- [x] Documenting the feature. https://github.com/wso2/identity-media/pull/22

**Phase 02 - Tasks:**

- [ ] Improvements to support multiple files (different representations of a resource) uploading.

[1] https://github.com/wso2/product-is/issues/6971
[2] https://github.com/wso2/identity-content-repository/tree/v1.0.3

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
