### ISSUE TITLE
Upgrade the OpenSAML version from OpenSAML2 to OpenSAML3

### ISSUE THREAD

**Issue by deshankoswatte** [wso2/product-is#8557]
**Description:**

Currently OpenSAML2 is used in the product which has reached its end of life 3 years back ([July 31, 2016](https://wiki.shibboleth.net/confluence/display/OpenSAML/Home)) for Java. Security fixes are no longer supported due to the situation we need to upgrade it to OpenSAML3 ASAP but doing so contains high complexities and extensive changes involved. This issue in order to track the sub issues which will in turn make this improvement a success.

**Tasks:**

The following are the main tasks that has been identified.

- [x] Upgrade SAML SSO related implementations into OpenSAML3. Tracked with https://github.com/wso2/product-is/issues/7156.
- [x] Provide WS-Trust functionality as a connector. Tracked with https://github.com/wso2/product-is/issues/8350.
- [x] Re implement WS-Federation using CXF. Tracked with https://github.com/wso2/product-is/issues/8350.
