### ISSUE TITLE
Add support to access SaaS applications through tenant qualified URLs

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#8568]
**Description**
* The SaaS applications should be accessible over the tenant qualified URLs

**Tasks**
- [ ] Introduce a new property for the service provider to enable it as a tenant-qualified SaaS application.
- [ ] Update the application REST API to support the new SP configuration
- [ ] Allow only the users of the tenant in given context path to log in to the application
- [ ] Sign the tokens issued using the certificate of the user's tenant

**Comment by omindu** [comment]
Will be addressed with https://github.com/wso2/product-is/issues/9531
