### ISSUE TITLE
Samples applications in product-is need to be migrated to the dedicated repo 

### ISSUE THREAD

**Issue by ashendes** [wso2/product-is#8638]
**Description:**
The sources of several sample applications exist as a separate module in the [product-is](https://github.com/wso2/product-is/) repo. They need to be moved to [samples-is](https://github.com/wso2/samples-is/), the repo dedicated to sample applications, to maintain consistency.

**Tasks to be done upon source code migration:**
- [x] Add moved samples to root pom of the sample-is
- [x] Check that the build works in samples-is
- [x] Add a readme file stating the samples have been moved
- [x] Confirm the documentations that refer to product-is samples are pointed to sample-is
- [x] Do a Samples-IS release before merging changes to the product
- [x] Fix the product-is build and integration tests to work with sample-is artifacts
- [x] Fix stale dependencies in product-is and samples-is
