### ISSUE TITLE
Upgrade third party dependencies

### ISSUE THREAD

**Issue by ashensw** [wso2/product-is#8641]
Upgrade third party dependencies

- [x] Update jackson databind to 2.10.x series and CXF to 3.4.0 or 3.3.5: https://github.com/wso2/product-is/issues/8005
- [x] Upgrade the common-codecs version: https://github.com/wso2/product-is/issues/8042
- [x] Upgrade handlebars-v4.0.11.js to latest version : https://github.com/wso2/product-is/issues/9259
- [x] https://github.com/wso2/product-is/issues/9360
- [x] https://github.com/wso2/product-is/issues/9362
- [x] https://github.com/wso2/product-is/issues/9368
- [x] https://github.com/wso2/product-is/issues/9369
- [x] https://github.com/wso2/product-is/issues/9276
- [x] https://github.com/wso2/product-is/issues/9520
- [x] https://github.com/wso2/product-is/issues/9523
- [x] https://github.com/wso2/product-is/issues/9528
- [x] https://github.com/wso2/product-is/issues/9542
- [x] https://github.com/wso2/product-is/issues/9569
- [x] https://github.com/wso2/product-is/issues/9596

Future tasks
- https://github.com/wso2/product-is/issues/7324
