### ISSUE TITLE
Implement Automation Unit Tests for Developer Portal and Admin Portal with Cypress Test Framework

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-is#8701]
#### Description

Cypress.io is the UI automation Framework for React. With this effort, automation unit tests will be implemented for the Developer Portal and Admin Portal covering the below main tasks. Purpose of this is to validate the behavior of each UI elements in the Developer Portal and Admin Portal

#### Task List

- [x] [Implement UI based Unit Tests for Developer Portal Applications Component](https://github.com/wso2/identity-apps/issues/1017)

- [x] [Implement UI based Unit Tests for Developer Portal Identity Provider Component](https://github.com/wso2/identity-apps/issues/1018)

- [x] [Implement UI based Unit Tests for Admin Portal Users Component](https://github.com/wso2/identity-apps/issues/1019)

- [x] [Implement UI based Unit Tests for Admin Portal Roles Component](https://github.com/wso2/identity-apps/issues/1020)

- [x] [Implement UI based Unit Tests for Admin Portal Groups Component](https://github.com/wso2/identity-apps/issues/1021)

- [x] [Implement UI based Unit Tests for Admin Portal Certificate Component](https://github.com/wso2/identity-apps/issues/1022)

- [x] [Implement UI based Unit Tests for Admin Portal Attribute Dialect Component](https://github.com/wso2/identity-apps/issues/1023)

- [x] [Implement UI based Unit Tests for Admin Portal UserStores Component](https://github.com/wso2/identity-apps/issues/1024)

- [x] [Implement UI based Unit Tests for Admin Portal Configurations Component](https://github.com/wso2/identity-apps/issues/1025)

- [ ] [Implement UI based Unit Tests for Admin Portal Attribute Management Component](https://github.com/wso2/identity-apps/issues/1026)
