### ISSUE TITLE
IDP Management in Developer Portal

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8727]
### Description

IDP management involves creating and managing identity providers in the system. The IDP management feature in the admin portal provides system administrators with a high-level view of currently existing IDPs, functionalities of each IDP, and their properties in the system. It enables system admins to make business-critical, real-time security decisions.

- [x] [Identity Provider Management - Configure Resident IDP](https://github.com/wso2/identity-apps/issues/363)
- [x] [Identity Provider Management - Design an info view for Identity Providers.](https://github.com/wso2/identity-apps/issues/361)
- [x] [Identity Provider Management - Implement advance search options for the identity providers list](https://github.com/wso2/identity-apps/issues/353)
- [x] [Identity Provider Management - Implement identity providers list sorting & filtering.](https://github.com/wso2/identity-apps/issues/352)
- [x] [Identity Provider Management - Create basic list view.](https://github.com/wso2/identity-apps/issues/351)
- [x] [Add localization support for IDP management](https://github.com/wso2/identity-apps/issues/992)
- [x] [Add authenticators view for the IDP management section](https://github.com/wso2/identity-apps/issues/993)
- [x] [Enhance IDP section with new API improvements](https://github.com/wso2/identity-apps/issues/995)
