### ISSUE TITLE
Configuration Management in Admin Portal

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8736]
**Description:**
Administrators should be able to manage the Configurations and Policies of the Resident Identity Provider. This UI will interact with the new [Server Configurations API](https://is.docs.wso2.com/en/5.11.0/develop/configs-rest-api/).

**Tasks:**
The following are the main tasks that has been identified.

- [x] [Implement Realm configurations section](https://github.com/wso2/product-is/issues/8751)
- [x] [Add Self Registration & Account Recovery sections](https://github.com/wso2/identity-apps/issues/581)
- [x] [Add Self signup configurations section](https://github.com/wso2/identity-apps/issues/581)
- [x] [Add Login Policies to Server Configurations](https://github.com/wso2/identity-apps/issues/648)
- [x] [Add Password Policies to Server Configurations](https://github.com/wso2/identity-apps/issues/1006)
- [x] [Change server configurations page design](https://github.com/wso2/identity-apps/issues/772)

**Future Improvements:**

[Implement capability to add Governance connectors](https://github.com/wso2/identity-apps/issues/1007)
