### ISSUE TITLE
Group Management in Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#8740]
#### Description

Group management allows you to configure and manage groups. A group contains a set of permissions for a collection of users to manage the server. You can create different groups with various combinations of permissions and assign them to a group of users. Through the admin portal, you can also edit and delete an existing group role.

#### Task List

- [x] [Support to create a new group](https://github.com/wso2/product-is/issues/8760)

- [x] [Add support to edit user groups](https://github.com/wso2/product-is/issues/8758)

- [x] [Support to assign a user to a group](https://github.com/wso2/product-is/issues/8757)

- [x] [Implement group permission view
](https://github.com/wso2/product-is/issues/8755)

- [x] [Implement group list view](https://github.com/wso2/product-is/issues/8753)

- [x] [Add avatar background to groups list](https://github.com/wso2/product-is/issues/8752)

- [x] [Add backward compatibility to align with the API](https://github.com/wso2/product-is/issues/9331)
