### ISSUE TITLE
Role Management in Console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#8742]
#### Description

Role management allows you to configure and manage roles as well as permission for a service provider. Roles contain permissions for users to manage the server. You can create different roles with various combinations of permissions and assign them to a user or a group of users. Through the admin portal, you can also edit and delete an existing user role.

#### Task List

- [x] [Support to create new role](https://github.com/wso2/product-is/issues/8792)

- [x] [Add support to edit user roles](https://github.com/wso2/product-is/issues/8789)

- [x] [Support to assign a user to a role](https://github.com/wso2/product-is/issues/8791)

- [x] [Implement role permission view](https://github.com/wso2/product-is/issues/8788)

- [x] [Add permission tree view](https://github.com/wso2/product-is/issues/8790)

- [x] [Implement role list view](https://github.com/wso2/product-is/issues/8794)

- [x] [Add avatar background to roles list
](https://github.com/wso2/product-is/issues/8783)

- [x] [Add backward compatibility to align with the API](https://github.com/wso2/product-is/issues/9331)
