### ISSUE TITLE
Userstore Management in Admin Portal

### ISSUE THREAD

**Issue by pamodaaw** [wso2/product-is#8744]
Description:
WSO2 Identity Server (WSO2 IS) should allow the admin users to view, create, and modify user stores for the system.

- [x] [Create a new user store](https://github.com/wso2/identity-apps/issues/349)
- [x] [Modify user store configurations](https://github.com/wso2/identity-apps/issues/350)
- [x] [Implement advance search options](https://github.com/wso2/product-is/issues/8845)
- [x] [Implement user store list sorting & filtering](https://github.com/wso2/product-is/issues/8846)
- [x] [Create Basic List View for userstores](https://github.com/wso2/product-is/issues/8849)

**TODO**

- [ ] [Improve UX to handle the userstore operations delay](https://github.com/wso2/identity-apps/issues/1013)

**Comment by brionmario** [comment]
Pending task will be tracked separately with #8725. Closing this issue in-favour of that.
