### ISSUE TITLE
Attribute Management feature in Admin Portal

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8772]
Implement attribute management in the admin portal to view, edit, and add local attributes, external attributes, and dialects.

- [x] [Implement external attributes](https://github.com/wso2/identity-apps/issues/587)
- [x] [Implement local attributes](https://github.com/wso2/identity-apps/issues/586)
- [x] [Implement attribute dialect view](https://github.com/wso2/identity-apps/issues/981)
- [x] [Add and edit attribute dialects](https://github.com/wso2/identity-apps/issues/590)
