### ISSUE TITLE
Re-design Admin & Developer Portal UIs

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#8873]
**Description:**
Since the Developer portal was split in to two i.e Admin & Developer[1], the overview pages needs to be redesigned. And the overall design in the two portals looks identical hence it doesn't give the user the feeling of switching between two separate applications. And the current design has lot of separators and a uniform background color. Using two background colors to play around with the Z-depth would be a better idea rather than the usage of separators. And also, the dynamic connectors pages needs to be styled.

[1] https://github.com/wso2/identity-apps/pull/951

**Mockups:**

![mockups](https://user-images.githubusercontent.com/25959096/87470862-0d7eb800-c63b-11ea-9d29-654373920ce6.png)

**Tasks:**
The following are the main tasks that has been identified.

- [x] Re-design Developer Portal overview page.
- [x] Integrate newly designed side panel variation.
- [x] Refactor theme to match mockups.
- [x] Re-design listing pages.
- [x] Re-design connector pages.
