### ISSUE TITLE
Claim verification and notification support for verifiable/sensitive claims

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8895]
An identity admin should be able to configure verifiable claims so that when these claims are updated, a verification or notification process should be triggered. 

Subtasks

- [ ] [Verify mobile claim on update](https://github.com/wso2/product-is/issues/9045)
- [x] [Verify email claim on update](https://github.com/wso2/product-is/issues/9046)
- [ ] [Notification support for sensitive claims on update](https://github.com/wso2/product-is/issues/8900)

**Comment by janakamarasena** [comment]
The Open Id Foundation is currently working on the specification "OpenID Connect for Identity Assurance 1.0" which aims to standardise the way verified claims are provided to RPs. This can also be used by the Identity Server to send information on verified claims.


https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
