### ISSUE TITLE
Implement application management UI in the user-portal

### ISSUE THREAD

**Issue by thivi** [wso2/product-is#8922]
The following UIs should be implemented as a part of the application page of the user-portal.

- [ ] [Implement a UI to allow users to manage their favourite applications in the user-portal](https://github.com/wso2/product-is/issues/8920) 
- [ ] [Implement a UI to allow users to manage application tags in the user-portal](https://github.com/wso2/product-is/issues/8921)

- [ ] [Let end user to tag applications based on user preference](https://github.com/wso2/product-is/issues/8915)

- [ ] [Define additional authentication factors for a Service Provider](https://github.com/wso2/product-is/issues/9770)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
