### ISSUE TITLE
Archetypes for extension points

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#8923]
**Problem definition**
IS has many extendable components/features which are widely used. Since we have defined structure, it is better to create archetypes to make the developers' life easier. 

**Preferred Solution**
Identify the most frequently used extension points and template them. The initial steps[1] for these efforts have been already taken place, we need to continue them.

[1]https://github.com/wso2-extensions/archetype-is

**Tasks**

- [x] Create a general structure for archetypes
- [x] Decide on versioning
- [ ] Update the current archetypes to latest dependencies
- [ ] Create documentation in the doc space
- [ ] Decide the pool of archetypes to be created
- [ ] Release them in the maven repository.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
