### ISSUE TITLE
Git Integration for login portal

### ISSUE THREAD

**Issue by inthirakumaaran** [wso2/product-is#9024]
**Problem definition**
Current way of introducing an update in authentication endpoint to a particular environment is by doing that change manually by changing the webapp.

This is an error prone approach and make the changes propagated through environments.

**Preferred Solution**
Having Identity Server capable of pulling webapp artifacts through its representation stored in a VCS like Github solve this. This will allow to automate changes automatically propagated through different environments, with correct CI\CD pipelines and test suits in place.

Retrieving the configuration updates can be done with both pull (periodic pulling), and push (with GitHub Webhook) models

**Tasks**

- [ ] Remote fetch support for IS
- [ ] VS Code extension to pull/push SPs
- [ ] VS code language server support to build adaptive authentication scripts
- [ ] Rest API for remote fetch service
- [ ] Add support for git hooks for GIT integration
- [ ] Add GIT integration UI to the developer portal
- [ ] Documentation

**Comment by ruwanta** [comment]
Ideally authentication portal should be able to be hosted in its own container. It can have its own build/deploy CI/CD pipeline.
Authentication portal should be broken down to APIs and the UI rendition. Then the UI part can have its own CI/CD process. then the git (VSC) pull idea is no longer becomes relevant.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
