### ISSUE TITLE
Refactor SSO Agent

### ISSUE THREAD

**Issue by ChamathNS** [wso2/product-is#9115]
**Description:**

In the current state, the SSO agent has the SAML2 and OIDC protocol libraries which are coupled together. So, in order to enrich the developer experience, it would be better to have these two protocols as seperate SDKs since then, the developers would need to write only a little amount of client side code since everything would be prebuilt and easily pluggable.

**Outcomes:**
The outcomes of this effort would be as follows,

1. Decouple SAML libraries and OIDC libraries
2. Facilitate engaging with apps by using only one dependency
3. Showcase authentication, user information retrieval and logout through sample apps for each protocol.

**Tasks:**

The following are the main tasks that has been identified for the initial phase of this effort.

SAML
- [ ] Create a sample app for testing SAML libraries

- [ ] Remove OIDC code and refactor the SSO agent code base to have only SAML libraries

- [ ] Refactor SAML libraries

OIDC
- [ ] Create a sample app for testing OIDC libraries

- [ ] Remove SAML code and refactor the SSO agent code base to have only OIDC libraries

- [ ] Refactor OIDC libraries

**Comment by ChamathNS** [comment]
The above mentioned tasks are captured in the development in following repositories.

https://github.com/asgardeo/asgardio-java-saml-sdk
https://github.com/asgardeo/asgardio-tomcat-saml-agent

https://github.com/asgardeo/asgardio-tomcat-oidc-agent
https://github.com/asgardeo/asgardio-java-oidc-sdk
