### ISSUE TITLE
Rename User Portal -> My Account

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9288]
**Is your feature request related to a problem? Please describe.**
The term user portal is contradicting with the use case and current features available in the portal.

**Describe the solution you would prefer**
`My Account` would be a better term for the portal.

**Tasks**
- [x] Rename the source code folder from `user-portal` -> `myaccount`. (wso2/identity-apps#1155)
- [x] Refactor portal configs in `carbon-identity-framework`. (wso2/carbon-identity-framework#3084)
- [x] Refactor app deployment configs(identity.xml) in `carbon-identity-framework`. (wso2/carbon-identity-framework#3084)
- [x] Refactor portal to distribution war names etc. in `product-is`. (wso2/product-is#9298)

**TODO**
- [ ] Add migration guide.
