### ISSUE TITLE
User Management in Admin Portal

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#9333]
#### Description

User management involves creating and managing users, roles, and access levels in a system. A user management feature in the admin portal provides system administrators with a high-level view of currently existing users, the privileges of each user, and their profiles in the system. It enables system admins to make business-critical, real-time security decisions. 

#### Task List

- [x] [Add user list search](https://github.com/wso2/identity-apps/issues/329)

- [x] [Support role assignment to the users](https://github.com/wso2/identity-apps/issues/336)

- [x] [Imeplement user list view](https://github.com/wso2/identity-apps/issues/321)

- [x] [Add user profile view](https://github.com/wso2/identity-apps/issues/331)

- [x] [List permissions of a user](https://github.com/wso2/identity-apps/issues/688)

- [x] [Add functionality to update user role list](https://github.com/wso2/identity-apps/issues/591)

- [x ] [Add backward compatibility to align with API level changes.](https://github.com/wso2/product-is/issues/9331)
