### ISSUE TITLE
Integration Tests for Console Features

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9394]
**Is your feature request related to a problem? Please describe.**
Currently, the features in console application doesn't have any integration tests.

**Tasks:**

Setting up the base

- [x] [Build a reusable base module for Cypress Tests.](https://github.com/wso2/product-is/issues/9663)
- [ ] [Publish Cypress base to the npm](https://github.com/wso2/product-is/issues/9791)
- [x] Build a structure to house integration tests.
- [x] [Create a pipeline to configure test suites.](https://github.com/wso2/product-is/issues/9664)

Test Suites

- [x] [Write integration tests for Application Management.](https://github.com/wso2/product-is/issues/9665)
- [x] [Write integration tests for IDP Management.](https://github.com/wso2/product-is/issues/9828)
- [ ] Write integration tests for Scope Management.
- [ ] [Write integration tests for Users.](https://github.com/wso2/product-is/issues/8863)
- [ ] [Write integration tests for Roles.](https://github.com/wso2/product-is/issues/8864)
- [ ] [Write integration tests for Groups.](https://github.com/wso2/product-is/issues/8865)
- [ ] [Write integration tests for Certificates.](https://github.com/wso2/product-is/issues/8866)
- [ ] [Write integration tests for Claims.](https://github.com/wso2/product-is/issues/8867)
- [ ] [Write integration tests for Userstores.](https://github.com/wso2/product-is/issues/8868)
- [x] [Write integration tests for Email Templates.](https://github.com/wso2/product-is/issues/9666)
- [ ] [Write integration tests for Server Configurations.](https://github.com/wso2/product-is/issues/8869)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
