### ISSUE TITLE
Modify app codebase to align with SaaS support

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9441]
**Describe the improvement**
Currently the Identity Server portals are registered as an application in each tenant. With wso2/product-is#9316, backend changes relevant to the improvement is carried out hence the changes needed to be done on the client side has to be done. 

**Tasks**
- [x] Implement function to extract `tenant_domain` from ID token.
- [x] Portals have to use super tenant urls for authorize, token, jwks, session, logout, commonauth.
- [x] After receiving the id_token, portals have to navigate the users to the relevant tenant URL.
- [x] Portals will access tenanted API endpoints for operations like applications, users etc.
