### ISSUE TITLE
Enhance My account and the login portal to view or hide UI widgets based on tenant level account management configuration preferences 

### ISSUE THREAD

**Issue by malithie** [wso2/product-is#9717]
**Is your feature request related to a problem? Please describe.**
There are capabilities/features that the tenant admin can enable based on the business use case such as,
- account recovery options
- self-registration options
- mobile/email verification options

Yet,  end-user interacting applications cannot produce the user experience on-demand per tenant, based on the above tenant admin preference configurations.
Eg:
Tenant admin can disable self signup and username recovery. When an end-user tries to log in to that tenant, signup
and username recovery options should be hidden from the login portal.

**Describe the solution you would prefer**

- Should implement a REST API with which the above tenant admin preferences can be retrieved by trusted applications to populate the UI.
- Need to identify topmost preferences that should be retrieved as of now. Can start with account management, login and recovery policies

Tasks

- [x] [ Create a REST API to retrieve tenant-level preferences](https://github.com/wso2/product-is/issues/9895)
- [x] [Use tenant-level preferences rest API to populate the login portal.](https://github.com/wso2/product-is/issues/9896)
- [ ] [Use tenant level preferences to populate the user portal](https://github.com/wso2/product-is/issues/9684) 

Effort BE::20
Effort FE::20

**Comment by ayshsandu** [comment]
Self-registration and account recovery options are not displayed based on the configurations provided at each tenant now. 
 **Pending: [Username and password pattern validation based on each tenant's user-store preferences](https://github.com/wso2/product-is/issues/11450)**
 
Mobile/email verification options at Myaccount are yet to be completed. Product level enhancements are needed to identify whether the email and mobile OTP options are enabled so that the relevant UI widgets need to be shown accordingly. Will be addressed in https://github.com/wso2/product-is/issues/9684
