### ISSUE TITLE
Supporting Email or Mobile as the Preferred Communication Channel 

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9754]
# Issue
Currently IS supports different types of communication channels such as Email, SMS etc. for second-factor authentication, but not for account confirmation and notification paths. Account confirmation and notification paths only work with Email as the communication channel.

This requirement is originally tracked in https://github.com/wso2/product-is/issues/6116

## Requirement
There are several scenarios, that need users' interaction to select a channel that they want to receive any kind of notification.

Therefore, the notification channel selection should be based on the following criteria.
- SMS : If the user have provided only the mobile number.
- Email : If the user have provided only the email address.
- Either SMS or Email : If the user have provided both mobile and email. In this case communication channel should be the preferred channel selected by the specific user.

# User scenarios associated with Multiple Communication Channels

### Backend support
- [x] User self-registration and account confirmation: https://github.com/wso2/product-is/issues/6339
- [x] User account recovery (Username and Password recovery) : https://github.com/wso2/product-is/issues/6343
- [ ] Notify on Failed Login Attempts : https://github.com/wso2/product-is/issues/9755
- [ ] Account Suspension : https://github.com/wso2/product-is/issues/9756

## UI requirement
- [ ] Self Registration with multiple channels where the user can select the preferred notification channel to be used in the future. 
**NOTE:** The requirement is specified in https://github.com/wso2/product-is/issues/9847
- [ ] Account recovery with multiple channels (Username and Password recovery) where the user can select the notification channel. : https://github.com/wso2/product-is/issues/9761

# Identity / IT admin scenarios associated with Multiple Communication Channels

- [ ] Onboard users with Email/SMS-based account verification and ask password : https://github.com/wso2/product-is/issues/9757
- [ ] Forced Password Reset with OTP (Both Email and SMS) : https://github.com/wso2/product-is/issues/9758 
- [ ] Lock a user account with notifications : https://github.com/wso2/product-is/issues/9759
- [ ] Disable a user account with notifications : https://github.com/wso2/product-is/issues/9760

## UI requirement
For the above requirements, existing UIs in the product can be used.

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
