### ISSUE TITLE
Email and SMS provider should be configurable by tenant wise. 

### ISSUE THREAD

**Issue by DimalChandrasiri** [wso2/product-is#9771]
Tenant admin should able to configure email, sms provider.

- An API to configure email providers per tenant
- UI support to configure email providers
- Ability to change email sender

**Total Effort**
- BE::30
   - Core: 20
   - Integration: 10
- FE::20

**Tasks:**

- [x] [Create swagger definition for tenant wise Notification Senders REST API](https://github.com/wso2/product-is/issues/10735)
- [x] [Implement the REST API core for the defined swagger definition](https://github.com/wso2/product-is/issues/10744)
- [ ] [Support capability to configure customMapping of SMSPublisher.xml via deployment.toml](https://github.com/wso2/product-is/issues/10859)
- [ ] [Implement UI support for Email and SMS notification sender configuration](https://github.com/wso2/product-is/issues/10748)
- [x] [Write integration test for the REST API and test the API with all DB types, API documentation](https://github.com/wso2/product-is/issues/10749)
- [ ] Document the feature capability

**Comment by somindatommy** [comment]
**Email**
- Email per tenant config: https://is.docs.wso2.com/en/5.11.0/learn/tenant-wise-email-sender-configuration/
- We can configure by using a separate publisher
- This feature does not have a UI

**SMS**
- SMS OTP: https://is.docs.wso2.com/en/5.11.0/learn/configuring-sms-otp/

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
