### ISSUE TITLE
Get the Cypress test base published to npm

### ISSUE THREAD

**Issue by brionmario** [wso2/product-is#9791]
**Is your feature request related to a problem? Please describe.**
Cypress test base is currently residing inside `identity-apps` and it has to accessible from other test repos as well. To do so, the module should be published to npm.

**Tasks**

- [x] Move https://github.com/wso2/identity-apps/tree/master/modules/cypress-base to a new repo.
- [x] Publish `@wso2is/cypress-base` to npm.
- [x] Refactor cypress base usage in identity apps.
