### ISSUE TITLE
Adaptive Authentication Flow Composer

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-is#9841]
**Is your feature request related to a problem? Please describe.**
- Building UX around identity is critical these days in order to stay competitive in the market. And the industry is leaning more towards visual approaches to make the products accessible by any level of users.

- With regards to Adaptive Authentication, WSO2 Identity Server currently supports script-based adaptive authentication, which allows users to use a script(Javascript) to set up appropriate authentication factors depending on the required scenario.

Currently we have a view for this. But we can improve it more to have better user experience.

![image](https://user-images.githubusercontent.com/7569427/95944518-fe5c0180-0e05-11eb-8f69-2675366f9af4.png)

**Describe the solution you would prefer**

- Develop a UI based tool where Identity Admins can design the adaptive authentication flow by using drag and drop components and providing any required parameters.

- This should help Identity admins to define the authentication flow with little to no prior scripting syntax knowledge.

- The tool at the background should generate or modify the authentication script which is currently being used and should do vice versa and update UI based flow if the script is updated directly.

Some view or tool like below,

![image](https://user-images.githubusercontent.com/7569427/95944583-1f245700-0e06-11eb-98d9-82d194c1b0a9.png)

**Comment by HimashiRathnayake** [comment]
**Tasks**
- [ ] Implement the base sidebar to hold Draggable Components

- [ ] Implement the drag and drop feature

- [ ] Implement the Script Editor

- [ ] Implement the feature to add conditions

- [ ] Implement the feature to define success flow and failure flow

- [ ] Implement the option to remove authentication factors and conditions

- [ ] Implement shift between script editor view and visual editor view

**Comment by jeradrutnam** [comment]
Initial PoC was done. And new IS 7.0 has a new composer based on this project and improvements will continue on that.

![image](https://github.com/wso2/product-is/assets/7569427/d6ac9c54-c0b1-4d87-b811-8b8ba4e49c39)
