### ISSUE TITLE
REST API to retrieve tenant level preferences #9717

### ISSUE THREAD

**Issue by IsuraD** [wso2/product-is#9895]
**Is your feature request related to a problem? Please describe.**
There are capabilities/features that the tenant admin can enable based on the business use case such as,
- account recovery options
- self-registration options
- mobile/email verification options

Yet,  end-user interacting applications cannot produce the user experience on-demand per tenant, based on the above tenant admin preference configurations.
Eg:
Tenant admin can disable self signup and username recovery. When an end-user tries to log in to that tenant, signup
and username recovery options should be hidden from the login portal.

**Describe the solution you would prefer**

- Should implement a REST API with which the above tenant admin preferences can be retrieved by trusted applications to populate the UI.
- Need to identify topmost preferences that should be retrieved as of now. Can start with account management, login and recovery policies

This is task is created to track the REST API implementation and its authentication/authorization 

Tasks

- [ ] [ Create REST API swagger definition](https://github.com/wso2/product-is/issues/10618)
- [ ] [Implement the core REST APIs for the defined swagger ](https://github.com/wso2/product-is/issues/10619)
- [ ] [Introduce a property to identify the secure properties in governance connectors](https://github.com/wso2/product-is/issues/10620) 
- [ ] [Write integration test for the REST API and test the API with all db types, documentation](https://github.com/wso2/product-is/issues/10621)

**Comment by nilasini** [comment]
Fixed with https://github.com/wso2/identity-api-server/pull/243,https://github.com/wso2/carbon-identity-framework/pull/3288,https://github.com/wso2-extensions/identity-governance/pull/466, https://github.com/wso2/identity-api-server/pull/246

Tests added with https://github.com/wso2/product-is/pull/10689
