### ISSUE TITLE
Improve user management feature in the console

### ISSUE THREAD

**Issue by NipuniBhagya** [wso2/product-is#9901]
**Is your suggestion related to an experience ? Please describe.**
We need to improve the user profile section to support the following functionalities. This will provide the administrators with more control over maintaining the user accounts.

**Task List:**

- [x] [Add user account lock capability](https://github.com/wso2/product-is/issues/9897)

- [x] [Implement user account disable functionality](https://github.com/wso2/product-is/issues/9898)

- [x] [Add functionality to change user account passwords](https://github.com/wso2/product-is/issues/9899)

- [x] [Implement force password reset functionality](https://github.com/wso2/product-is/issues/10191)
