### ISSUE TITLE
Improving test coverage

### ISSUE THREAD

**Issue by somindatommy** [wso2/product-is#9959]
### **Describe the issue:**
Even though there are test scenarios, those tests do not cover all the sub scenarios connected to the main scenario. Therefore, test coverage needs to be improved to cover any sub scenarios related to the main scenarios.

### Tasks
- [ ] Improving test coverage for SCIM scenarios. Some special cases are as follows.
   - [ ] validate user listing with pagination
   - [ ] validate user filtering with pagination
   - [ ] validating legacy behavior support (returning all the results for not specified list param)

**Comment by isharak** [comment]
This issue is being closed due to extended inactivity. Please feel free to reopen it if further attention is needed. Thank you for helping us keep the issue list relevant and focused!
